#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$ROOT_DIR/scripts/swiftpm-profile-auto-layout.sh"
source "$ROOT_DIR/scripts/swiftpm-profile-local-imports.sh"
source "$ROOT_DIR/scripts/swiftpm-profile-lowered-source-cache.sh"
SOURCE_DIR="${QUILLUI_PROFILE_SOURCE_DIR:-}"
WORK_ROOT="${QUILLUI_PROFILE_WORKDIR:-}"
PRODUCT_NAME="${QUILLUI_PROFILE_PRODUCT_NAME:-generic-swiftui-linux}"
PACKAGE_NAME="${QUILLUI_PROFILE_PACKAGE_NAME:-GeneratedSwiftUILinuxApp}"
TARGET_NAME="${QUILLUI_PROFILE_TARGET_NAME:-GeneratedSwiftUILinuxApp}"
ENTRY_TYPE="${QUILLUI_PROFILE_ENTRY_TYPE:-}"
MAIN_TYPE="${QUILLUI_PROFILE_MAIN_TYPE:-GeneratedSwiftUILinuxMain}"
BACKEND_FACADE="${QUILLUI_GENERATED_BACKEND_FACADE:-swiftui}"
QT_RUNTIME_MODE="${QUILLUI_GENERATED_QT_RUNTIME_MODE:-auto}"
QT_NATIVE_CATALOG_ENTRY="${QUILLUI_GENERATED_QT_NATIVE_CATALOG_ENTRY:-}"
LOWERED_SOURCE_CACHE_DIR="${QUILLUI_PROFILE_LOWERED_SOURCE_CACHE_DIR:-$ROOT_DIR/.build/quillui-lowered-source-cache}"
REUSE_LOWERED_SOURCE="${QUILLUI_PROFILE_REUSE_LOWERED_SOURCE:-1}"
PREPARED_PACKAGE_CACHE_DIR="${QUILLUI_PROFILE_PREPARED_PACKAGE_CACHE_DIR:-${QUILLUI_GENERATED_PREPARED_PACKAGE_CACHE_DIR:-$ROOT_DIR/.build/quillui-prepared-packages-cache}}"
PACKAGE_DIR="$WORK_ROOT/package"
quillui_profile_validate_generic_swiftui_inputs "$SOURCE_DIR" "$WORK_ROOT" "$ENTRY_TYPE" "$BACKEND_FACADE" "$ROOT_DIR"
mkdir -p "$WORK_ROOT"
quillui_profile_prepare_lowered_source "$ROOT_DIR" "$SOURCE_DIR" "$WORK_ROOT" "$LOWERED_SOURCE_CACHE_DIR" "$REUSE_LOWERED_SOURCE"
SOURCE_COPY="$QUILLUI_PROFILE_SOURCE_COPY"
LOWERED_COPY="$QUILLUI_PROFILE_LOWERED_COPY"
quillui_profile_maybe_derive_swiftpm_layout "$ROOT_DIR" "$SOURCE_DIR" "$WORK_ROOT" "$ENTRY_TYPE" "$TARGET_NAME"
quillui_profile_maybe_discover_local_import_dependencies "$ROOT_DIR" "$LOWERED_COPY" "$WORK_ROOT"
QUILLUI_GENERATED_SOURCES_DIR="$LOWERED_COPY" \
QUILLUI_GENERATED_SOURCE_COUNT_DIR="$SOURCE_COPY" \
QUILLUI_GENERATED_WORKDIR="$WORK_ROOT" \
QUILLUI_GENERATED_PACKAGE_DIR="$PACKAGE_DIR" \
QUILLUI_GENERATED_PACKAGE_NAME="$PACKAGE_NAME" \
QUILLUI_GENERATED_PRODUCT_NAME="$PRODUCT_NAME" \
QUILLUI_GENERATED_TARGET_NAME="$TARGET_NAME" \
QUILLUI_GENERATED_INCLUDE_BACKEND_ENTRY=1 \
QUILLUI_GENERATED_APP_ENTRY_TYPE="$ENTRY_TYPE" \
QUILLUI_GENERATED_APP_MAIN_TYPE="$MAIN_TYPE" \
QUILLUI_GENERATED_PREPARED_PACKAGE_CACHE_DIR="$PREPARED_PACKAGE_CACHE_DIR" \
QUILLUI_GENERATED_QT_RUNTIME_MODE="$QT_RUNTIME_MODE" \
QUILLUI_GENERATED_QT_NATIVE_CATALOG_ENTRY="$QT_NATIVE_CATALOG_ENTRY" \
QUILLUI_REQUIRE_VENDORED_SOURCES="${QUILLUI_REQUIRE_VENDORED_SOURCES:-1}" \
QUILLUI_GENERATED_REPORT_LABEL="Generated generic SwiftUI Linux app" \
"$ROOT_DIR/scripts/generate-swiftui-linux-package.sh"
