// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_InstantPage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case blocks = 4
    case media = 6
    case isComplete = 8
    case rtl = 10
    case url = 12
    case views = 14
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasBlocks: Bool { let o = _accessor.offset(VTOFFSET.blocks.v); return o == 0 ? false : true }
  public var blocksCount: Int32 { let o = _accessor.offset(VTOFFSET.blocks.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func blocks(at index: Int32) -> TelegramCore_InstantPageBlock? { let o = _accessor.offset(VTOFFSET.blocks.v); return o == 0 ? nil : TelegramCore_InstantPageBlock(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasMedia: Bool { let o = _accessor.offset(VTOFFSET.media.v); return o == 0 ? false : true }
  public var mediaCount: Int32 { let o = _accessor.offset(VTOFFSET.media.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func media(at index: Int32) -> TelegramCore_Media? { let o = _accessor.offset(VTOFFSET.media.v); return o == 0 ? nil : TelegramCore_Media(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var isComplete: Bool { let o = _accessor.offset(VTOFFSET.isComplete.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var rtl: Bool { let o = _accessor.offset(VTOFFSET.rtl.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var url: String! { let o = _accessor.offset(VTOFFSET.url.v); return _accessor.string(at: o) }
  public var urlSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.url.v) }
  public var views: Int32 { let o = _accessor.offset(VTOFFSET.views.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startInstantPage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 6) }
  public static func addVectorOf(blocks: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: blocks, at: VTOFFSET.blocks.p) }
  public static func addVectorOf(media: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: media, at: VTOFFSET.media.p) }
  public static func add(isComplete: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isComplete, def: false,
   at: VTOFFSET.isComplete.p) }
  public static func add(rtl: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: rtl, def: false,
   at: VTOFFSET.rtl.p) }
  public static func add(url: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: url, at: VTOFFSET.url.p) }
  public static func add(views: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: views, def: 0, at: VTOFFSET.views.p) }
  public static func endInstantPage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6, 12]); return end }
  public static func createInstantPage(
    _ fbb: inout FlatBufferBuilder,
    blocksVectorOffset blocks: Offset,
    mediaVectorOffset media: Offset,
    isComplete: Bool = false,
    rtl: Bool = false,
    urlOffset url: Offset,
    views: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_InstantPage.startInstantPage(&fbb)
    TelegramCore_InstantPage.addVectorOf(blocks: blocks, &fbb)
    TelegramCore_InstantPage.addVectorOf(media: media, &fbb)
    TelegramCore_InstantPage.add(isComplete: isComplete, &fbb)
    TelegramCore_InstantPage.add(rtl: rtl, &fbb)
    TelegramCore_InstantPage.add(url: url, &fbb)
    TelegramCore_InstantPage.add(views: views, &fbb)
    return TelegramCore_InstantPage.endInstantPage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.blocks.p, fieldName: "blocks", required: true, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_InstantPageBlock>, TelegramCore_InstantPageBlock>>.self)
    try _v.visit(field: VTOFFSET.media.p, fieldName: "media", required: true, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_Media>, TelegramCore_Media>>.self)
    try _v.visit(field: VTOFFSET.isComplete.p, fieldName: "isComplete", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.rtl.p, fieldName: "rtl", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.url.p, fieldName: "url", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.views.p, fieldName: "views", required: false, type: Int32.self)
    _v.finish()
  }
}

