// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_ItemCollectionId: NativeStruct, Verifiable, FlatbuffersInitializable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }

  private var _namespace: Int32
  private let padding0__: UInt32 = 0
  private var _id: Int64

  public init(_ bb: ByteBuffer, o: Int32) {
    let _accessor = Struct(bb: bb, position: o)
    _namespace = _accessor.readBuffer(of: Int32.self, at: 0)
    _id = _accessor.readBuffer(of: Int64.self, at: 8)
  }

  public init(namespace: Int32, id: Int64) {
    _namespace = namespace
    _id = id
  }

  public init() {
    _namespace = 0
    _id = 0
  }

  public var namespace: Int32 { _namespace }
  public var id: Int64 { _id }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    try verifier.inBuffer(position: position, of: TelegramCore_ItemCollectionId.self)
  }
}

public struct TelegramCore_ItemCollectionId_Mutable: FlatBufferObject {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Struct

  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Struct(bb: bb, position: o) }

  public var namespace: Int32 { return _accessor.readBuffer(of: Int32.self, at: 0) }
  public var id: Int64 { return _accessor.readBuffer(of: Int64.self, at: 8) }
}
