// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_Media_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case mediaTelegrammediafile = 1
  case mediaTelegrammediaimage = 2

  public static var max: TelegramCore_Media_Value { return .mediaTelegrammediaimage }
  public static var min: TelegramCore_Media_Value { return .none_ }
}


public struct TelegramCore_Media: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_Media_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_Media_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startMedia(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_Media_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endMedia(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createMedia(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_Media_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_Media.startMedia(&fbb)
    TelegramCore_Media.add(valueType: valueType, &fbb)
    TelegramCore_Media.add(value: value, &fbb)
    return TelegramCore_Media.endMedia(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_Media_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .mediaTelegrammediafile:
        try ForwardOffset<TelegramCore_Media_TelegramMediaFile>.verify(&verifier, at: pos, of: TelegramCore_Media_TelegramMediaFile.self)
      case .mediaTelegrammediaimage:
        try ForwardOffset<TelegramCore_Media_TelegramMediaImage>.verify(&verifier, at: pos, of: TelegramCore_Media_TelegramMediaImage.self)
      }
    })
    _v.finish()
  }
}

public struct TelegramCore_Media_TelegramMediaFile: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case file = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var file: TelegramCore_TelegramMediaFile! { let o = _accessor.offset(VTOFFSET.file.v); return TelegramCore_TelegramMediaFile(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startMedia_TelegramMediaFile(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(file: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: file, at: VTOFFSET.file.p) }
  public static func endMedia_TelegramMediaFile(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createMedia_TelegramMediaFile(
    _ fbb: inout FlatBufferBuilder,
    fileOffset file: Offset
  ) -> Offset {
    let __start = TelegramCore_Media_TelegramMediaFile.startMedia_TelegramMediaFile(&fbb)
    TelegramCore_Media_TelegramMediaFile.add(file: file, &fbb)
    return TelegramCore_Media_TelegramMediaFile.endMedia_TelegramMediaFile(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.file.p, fieldName: "file", required: true, type: ForwardOffset<TelegramCore_TelegramMediaFile>.self)
    _v.finish()
  }
}

public struct TelegramCore_Media_TelegramMediaImage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case image = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var image: TelegramCore_TelegramMediaImage! { let o = _accessor.offset(VTOFFSET.image.v); return TelegramCore_TelegramMediaImage(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startMedia_TelegramMediaImage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(image: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: image, at: VTOFFSET.image.p) }
  public static func endMedia_TelegramMediaImage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createMedia_TelegramMediaImage(
    _ fbb: inout FlatBufferBuilder,
    imageOffset image: Offset
  ) -> Offset {
    let __start = TelegramCore_Media_TelegramMediaImage.startMedia_TelegramMediaImage(&fbb)
    TelegramCore_Media_TelegramMediaImage.add(image: image, &fbb)
    return TelegramCore_Media_TelegramMediaImage.endMedia_TelegramMediaImage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.image.p, fieldName: "image", required: true, type: ForwardOffset<TelegramCore_TelegramMediaImage>.self)
    _v.finish()
  }
}

