// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_MessageId: NativeStruct, Verifiable, FlatbuffersInitializable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }

  private var _peerId: TelegramCore_PeerId
  private var _namespace: Int32
  private var _id: Int32

  public init(_ bb: ByteBuffer, o: Int32) {
    let _accessor = Struct(bb: bb, position: o)
    _peerId = TelegramCore_PeerId(_accessor.bb, o: _accessor.position + 0)
    _namespace = _accessor.readBuffer(of: Int32.self, at: 16)
    _id = _accessor.readBuffer(of: Int32.self, at: 20)
  }

  public init(peerId: TelegramCore_PeerId, namespace: Int32, id: Int32) {
    _peerId = peerId
    _namespace = namespace
    _id = id
  }

  public init() {
    _peerId = TelegramCore_PeerId()
    _namespace = 0
    _id = 0
  }

  public var peerId: TelegramCore_PeerId { _peerId }
  public var namespace: Int32 { _namespace }
  public var id: Int32 { _id }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    try verifier.inBuffer(position: position, of: TelegramCore_MessageId.self)
  }
}

public struct TelegramCore_MessageId_Mutable: FlatBufferObject {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Struct

  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Struct(bb: bb, position: o) }

  public var peerId: TelegramCore_PeerId_Mutable { return TelegramCore_PeerId_Mutable(_accessor.bb, o: _accessor.position + 0) }
  public var namespace: Int32 { return _accessor.readBuffer(of: Int32.self, at: 16) }
  public var id: Int32 { return _accessor.readBuffer(of: Int32.self, at: 20) }
}
