// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_OptionalBool: NativeStruct, Verifiable, FlatbuffersInitializable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }

  private var _value: Bool

  public init(_ bb: ByteBuffer, o: Int32) {
    let _accessor = Struct(bb: bb, position: o)
    _value = _accessor.readBuffer(of: Bool.self, at: 0)
  }

  public init(value: Bool) {
    _value = value
  }

  public init() {
    _value = false
  }

  public var value: Bool { _value }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    try verifier.inBuffer(position: position, of: TelegramCore_OptionalBool.self)
  }
}

public struct TelegramCore_OptionalBool_Mutable: FlatBufferObject {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Struct

  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Struct(bb: bb, position: o) }

  public var value: Bool { return _accessor.readBuffer(of: Bool.self, at: 0) }
}

