// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_PartialMediaReference_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case partialmediareferenceMessage = 1
  case partialmediareferenceWebpage = 2
  case partialmediareferenceStickerpack = 3
  case partialmediareferenceSavedgif = 4
  case partialmediareferenceSavedsticker = 5
  case partialmediareferenceRecentsticker = 6

  public static var max: TelegramCore_PartialMediaReference_Value { return .partialmediareferenceRecentsticker }
  public static var min: TelegramCore_PartialMediaReference_Value { return .none_ }
}


public struct TelegramCore_MessageReference: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case peer = 4
    case author = 6
    case messageId = 8
    case timestamp = 10
    case incoming = 12
    case secret = 14
    case threadId = 16
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var peer: TelegramCore_PeerReference! { let o = _accessor.offset(VTOFFSET.peer.v); return TelegramCore_PeerReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var author: TelegramCore_PeerReference? { let o = _accessor.offset(VTOFFSET.author.v); return o == 0 ? nil : TelegramCore_PeerReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var messageId: TelegramCore_MessageId! { let o = _accessor.offset(VTOFFSET.messageId.v); return _accessor.readBuffer(of: TelegramCore_MessageId.self, at: o) }
  public var mutableMessageId: TelegramCore_MessageId_Mutable! { let o = _accessor.offset(VTOFFSET.messageId.v); return TelegramCore_MessageId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var timestamp: Int32 { let o = _accessor.offset(VTOFFSET.timestamp.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var incoming: Bool { let o = _accessor.offset(VTOFFSET.incoming.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var secret: Bool { let o = _accessor.offset(VTOFFSET.secret.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var threadId: Int64 { let o = _accessor.offset(VTOFFSET.threadId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startMessageReference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 7) }
  public static func add(peer: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: peer, at: VTOFFSET.peer.p) }
  public static func add(author: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: author, at: VTOFFSET.author.p) }
  public static func add(messageId: TelegramCore_MessageId?, _ fbb: inout FlatBufferBuilder) { guard let messageId = messageId else { return }; fbb.create(struct: messageId, position: VTOFFSET.messageId.p) }
  public static func add(timestamp: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: timestamp, def: 0, at: VTOFFSET.timestamp.p) }
  public static func add(incoming: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: incoming, def: false,
   at: VTOFFSET.incoming.p) }
  public static func add(secret: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: secret, def: false,
   at: VTOFFSET.secret.p) }
  public static func add(threadId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: threadId, def: 0, at: VTOFFSET.threadId.p) }
  public static func endMessageReference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 8]); return end }
  public static func createMessageReference(
    _ fbb: inout FlatBufferBuilder,
    peerOffset peer: Offset,
    authorOffset author: Offset = Offset(),
    messageId: TelegramCore_MessageId,
    timestamp: Int32 = 0,
    incoming: Bool = false,
    secret: Bool = false,
    threadId: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_MessageReference.startMessageReference(&fbb)
    TelegramCore_MessageReference.add(peer: peer, &fbb)
    TelegramCore_MessageReference.add(author: author, &fbb)
    TelegramCore_MessageReference.add(messageId: messageId, &fbb)
    TelegramCore_MessageReference.add(timestamp: timestamp, &fbb)
    TelegramCore_MessageReference.add(incoming: incoming, &fbb)
    TelegramCore_MessageReference.add(secret: secret, &fbb)
    TelegramCore_MessageReference.add(threadId: threadId, &fbb)
    return TelegramCore_MessageReference.endMessageReference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.peer.p, fieldName: "peer", required: true, type: ForwardOffset<TelegramCore_PeerReference>.self)
    try _v.visit(field: VTOFFSET.author.p, fieldName: "author", required: false, type: ForwardOffset<TelegramCore_PeerReference>.self)
    try _v.visit(field: VTOFFSET.messageId.p, fieldName: "messageId", required: true, type: TelegramCore_MessageId.self)
    try _v.visit(field: VTOFFSET.timestamp.p, fieldName: "timestamp", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.incoming.p, fieldName: "incoming", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.secret.p, fieldName: "secret", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.threadId.p, fieldName: "threadId", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_WebpageReference: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case webpageId = 4
    case url = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var webpageId: Int64 { let o = _accessor.offset(VTOFFSET.webpageId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var url: String! { let o = _accessor.offset(VTOFFSET.url.v); return _accessor.string(at: o) }
  public var urlSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.url.v) }
  public static func startWebpageReference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(webpageId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: webpageId, def: 0, at: VTOFFSET.webpageId.p) }
  public static func add(url: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: url, at: VTOFFSET.url.p) }
  public static func endWebpageReference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createWebpageReference(
    _ fbb: inout FlatBufferBuilder,
    webpageId: Int64 = 0,
    urlOffset url: Offset
  ) -> Offset {
    let __start = TelegramCore_WebpageReference.startWebpageReference(&fbb)
    TelegramCore_WebpageReference.add(webpageId: webpageId, &fbb)
    TelegramCore_WebpageReference.add(url: url, &fbb)
    return TelegramCore_WebpageReference.endWebpageReference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.webpageId.p, fieldName: "webpageId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.url.p, fieldName: "url", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_PartialMediaReference_Message: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case message = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var message: TelegramCore_MessageReference? { let o = _accessor.offset(VTOFFSET.message.v); return o == 0 ? nil : TelegramCore_MessageReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startPartialMediaReference_Message(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(message: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: message, at: VTOFFSET.message.p) }
  public static func endPartialMediaReference_Message(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPartialMediaReference_Message(
    _ fbb: inout FlatBufferBuilder,
    messageOffset message: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_PartialMediaReference_Message.startPartialMediaReference_Message(&fbb)
    TelegramCore_PartialMediaReference_Message.add(message: message, &fbb)
    return TelegramCore_PartialMediaReference_Message.endPartialMediaReference_Message(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.message.p, fieldName: "message", required: false, type: ForwardOffset<TelegramCore_MessageReference>.self)
    _v.finish()
  }
}

public struct TelegramCore_PartialMediaReference_WebPage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case webPage = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var webPage: TelegramCore_WebpageReference? { let o = _accessor.offset(VTOFFSET.webPage.v); return o == 0 ? nil : TelegramCore_WebpageReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startPartialMediaReference_WebPage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(webPage: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: webPage, at: VTOFFSET.webPage.p) }
  public static func endPartialMediaReference_WebPage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPartialMediaReference_WebPage(
    _ fbb: inout FlatBufferBuilder,
    webPageOffset webPage: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_PartialMediaReference_WebPage.startPartialMediaReference_WebPage(&fbb)
    TelegramCore_PartialMediaReference_WebPage.add(webPage: webPage, &fbb)
    return TelegramCore_PartialMediaReference_WebPage.endPartialMediaReference_WebPage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.webPage.p, fieldName: "webPage", required: false, type: ForwardOffset<TelegramCore_WebpageReference>.self)
    _v.finish()
  }
}

public struct TelegramCore_PartialMediaReference_StickerPack: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case stickerPack = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var stickerPack: TelegramCore_StickerPackReference! { let o = _accessor.offset(VTOFFSET.stickerPack.v); return TelegramCore_StickerPackReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startPartialMediaReference_StickerPack(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(stickerPack: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: stickerPack, at: VTOFFSET.stickerPack.p) }
  public static func endPartialMediaReference_StickerPack(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createPartialMediaReference_StickerPack(
    _ fbb: inout FlatBufferBuilder,
    stickerPackOffset stickerPack: Offset
  ) -> Offset {
    let __start = TelegramCore_PartialMediaReference_StickerPack.startPartialMediaReference_StickerPack(&fbb)
    TelegramCore_PartialMediaReference_StickerPack.add(stickerPack: stickerPack, &fbb)
    return TelegramCore_PartialMediaReference_StickerPack.endPartialMediaReference_StickerPack(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.stickerPack.p, fieldName: "stickerPack", required: true, type: ForwardOffset<TelegramCore_StickerPackReference>.self)
    _v.finish()
  }
}

public struct TelegramCore_PartialMediaReference_SavedGif: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startPartialMediaReference_SavedGif(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endPartialMediaReference_SavedGif(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_PartialMediaReference_SavedSticker: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startPartialMediaReference_SavedSticker(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endPartialMediaReference_SavedSticker(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_PartialMediaReference_RecentSticker: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startPartialMediaReference_RecentSticker(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endPartialMediaReference_RecentSticker(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_PartialMediaReference: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_PartialMediaReference_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_PartialMediaReference_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startPartialMediaReference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_PartialMediaReference_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endPartialMediaReference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createPartialMediaReference(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_PartialMediaReference_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_PartialMediaReference.startPartialMediaReference(&fbb)
    TelegramCore_PartialMediaReference.add(valueType: valueType, &fbb)
    TelegramCore_PartialMediaReference.add(value: value, &fbb)
    return TelegramCore_PartialMediaReference.endPartialMediaReference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_PartialMediaReference_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .partialmediareferenceMessage:
        try ForwardOffset<TelegramCore_PartialMediaReference_Message>.verify(&verifier, at: pos, of: TelegramCore_PartialMediaReference_Message.self)
      case .partialmediareferenceWebpage:
        try ForwardOffset<TelegramCore_PartialMediaReference_WebPage>.verify(&verifier, at: pos, of: TelegramCore_PartialMediaReference_WebPage.self)
      case .partialmediareferenceStickerpack:
        try ForwardOffset<TelegramCore_PartialMediaReference_StickerPack>.verify(&verifier, at: pos, of: TelegramCore_PartialMediaReference_StickerPack.self)
      case .partialmediareferenceSavedgif:
        try ForwardOffset<TelegramCore_PartialMediaReference_SavedGif>.verify(&verifier, at: pos, of: TelegramCore_PartialMediaReference_SavedGif.self)
      case .partialmediareferenceSavedsticker:
        try ForwardOffset<TelegramCore_PartialMediaReference_SavedSticker>.verify(&verifier, at: pos, of: TelegramCore_PartialMediaReference_SavedSticker.self)
      case .partialmediareferenceRecentsticker:
        try ForwardOffset<TelegramCore_PartialMediaReference_RecentSticker>.verify(&verifier, at: pos, of: TelegramCore_PartialMediaReference_RecentSticker.self)
      }
    })
    _v.finish()
  }
}
