// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_RestrictionRule: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case platform = 4
    case reason = 6
    case text = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var platform: String! { let o = _accessor.offset(VTOFFSET.platform.v); return _accessor.string(at: o) }
  public var platformSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.platform.v) }
  public var reason: String! { let o = _accessor.offset(VTOFFSET.reason.v); return _accessor.string(at: o) }
  public var reasonSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.reason.v) }
  public var text: String! { let o = _accessor.offset(VTOFFSET.text.v); return _accessor.string(at: o) }
  public var textSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.text.v) }
  public static func startRestrictionRule(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(platform: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: platform, at: VTOFFSET.platform.p) }
  public static func add(reason: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: reason, at: VTOFFSET.reason.p) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRestrictionRule(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6, 8]); return end }
  public static func createRestrictionRule(
    _ fbb: inout FlatBufferBuilder,
    platformOffset platform: Offset,
    reasonOffset reason: Offset,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RestrictionRule.startRestrictionRule(&fbb)
    TelegramCore_RestrictionRule.add(platform: platform, &fbb)
    TelegramCore_RestrictionRule.add(reason: reason, &fbb)
    TelegramCore_RestrictionRule.add(text: text, &fbb)
    return TelegramCore_RestrictionRule.endRestrictionRule(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.platform.p, fieldName: "platform", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.reason.p, fieldName: "reason", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_PeerAccessRestrictionInfo: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case rules = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasRules: Bool { let o = _accessor.offset(VTOFFSET.rules.v); return o == 0 ? false : true }
  public var rulesCount: Int32 { let o = _accessor.offset(VTOFFSET.rules.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func rules(at index: Int32) -> TelegramCore_RestrictionRule? { let o = _accessor.offset(VTOFFSET.rules.v); return o == 0 ? nil : TelegramCore_RestrictionRule(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public static func startPeerAccessRestrictionInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func addVectorOf(rules: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: rules, at: VTOFFSET.rules.p) }
  public static func endPeerAccessRestrictionInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createPeerAccessRestrictionInfo(
    _ fbb: inout FlatBufferBuilder,
    rulesVectorOffset rules: Offset
  ) -> Offset {
    let __start = TelegramCore_PeerAccessRestrictionInfo.startPeerAccessRestrictionInfo(&fbb)
    TelegramCore_PeerAccessRestrictionInfo.addVectorOf(rules: rules, &fbb)
    return TelegramCore_PeerAccessRestrictionInfo.endPeerAccessRestrictionInfo(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.rules.p, fieldName: "rules", required: true, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_RestrictionRule>, TelegramCore_RestrictionRule>>.self)
    _v.finish()
  }
}

