// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_PeerReference_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case peerreferenceUser = 1
  case peerreferenceGroup = 2
  case peerreferenceChannel = 3

  public static var max: TelegramCore_PeerReference_Value { return .peerreferenceChannel }
  public static var min: TelegramCore_PeerReference_Value { return .none_ }
}


public struct TelegramCore_PeerReference_User: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case accessHash = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: Int64 { let o = _accessor.offset(VTOFFSET.id.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startPeerReference_User(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(id: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: id, def: 0, at: VTOFFSET.id.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func endPeerReference_User(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPeerReference_User(
    _ fbb: inout FlatBufferBuilder,
    id: Int64 = 0,
    accessHash: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_PeerReference_User.startPeerReference_User(&fbb)
    TelegramCore_PeerReference_User.add(id: id, &fbb)
    TelegramCore_PeerReference_User.add(accessHash: accessHash, &fbb)
    return TelegramCore_PeerReference_User.endPeerReference_User(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_PeerReference_Group: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: Int64 { let o = _accessor.offset(VTOFFSET.id.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startPeerReference_Group(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(id: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: id, def: 0, at: VTOFFSET.id.p) }
  public static func endPeerReference_Group(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPeerReference_Group(
    _ fbb: inout FlatBufferBuilder,
    id: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_PeerReference_Group.startPeerReference_Group(&fbb)
    TelegramCore_PeerReference_Group.add(id: id, &fbb)
    return TelegramCore_PeerReference_Group.endPeerReference_Group(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_PeerReference_Channel: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case accessHash = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: Int64 { let o = _accessor.offset(VTOFFSET.id.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startPeerReference_Channel(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(id: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: id, def: 0, at: VTOFFSET.id.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func endPeerReference_Channel(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPeerReference_Channel(
    _ fbb: inout FlatBufferBuilder,
    id: Int64 = 0,
    accessHash: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_PeerReference_Channel.startPeerReference_Channel(&fbb)
    TelegramCore_PeerReference_Channel.add(id: id, &fbb)
    TelegramCore_PeerReference_Channel.add(accessHash: accessHash, &fbb)
    return TelegramCore_PeerReference_Channel.endPeerReference_Channel(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_PeerReference: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_PeerReference_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_PeerReference_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startPeerReference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_PeerReference_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endPeerReference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createPeerReference(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_PeerReference_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_PeerReference.startPeerReference(&fbb)
    TelegramCore_PeerReference.add(valueType: valueType, &fbb)
    TelegramCore_PeerReference.add(value: value, &fbb)
    return TelegramCore_PeerReference.endPeerReference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_PeerReference_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .peerreferenceUser:
        try ForwardOffset<TelegramCore_PeerReference_User>.verify(&verifier, at: pos, of: TelegramCore_PeerReference_User.self)
      case .peerreferenceGroup:
        try ForwardOffset<TelegramCore_PeerReference_Group>.verify(&verifier, at: pos, of: TelegramCore_PeerReference_Group.self)
      case .peerreferenceChannel:
        try ForwardOffset<TelegramCore_PeerReference_Channel>.verify(&verifier, at: pos, of: TelegramCore_PeerReference_Channel.self)
      }
    })
    _v.finish()
  }
}

