// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_PeerEmojiStatusContent_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case peeremojistatuscontentemoji = 1
  case peeremojistatuscontentstargift = 2

  public static var max: TelegramCore_PeerEmojiStatusContent_Value { return .peeremojistatuscontentstargift }
  public static var min: TelegramCore_PeerEmojiStatusContent_Value { return .none_ }
}


public struct TelegramCore_PeerEmojiStatusContentEmoji: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case fileId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var fileId: Int64 { let o = _accessor.offset(VTOFFSET.fileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startPeerEmojiStatusContentEmoji(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(fileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fileId, def: 0, at: VTOFFSET.fileId.p) }
  public static func endPeerEmojiStatusContentEmoji(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPeerEmojiStatusContentEmoji(
    _ fbb: inout FlatBufferBuilder,
    fileId: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_PeerEmojiStatusContentEmoji.startPeerEmojiStatusContentEmoji(&fbb)
    TelegramCore_PeerEmojiStatusContentEmoji.add(fileId: fileId, &fbb)
    return TelegramCore_PeerEmojiStatusContentEmoji.endPeerEmojiStatusContentEmoji(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.fileId.p, fieldName: "fileId", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_PeerEmojiStatusContentStarGift: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case fileId = 6
    case title = 8
    case slug = 10
    case patternFileId = 12
    case innerColor = 14
    case outerColor = 16
    case patternColor = 18
    case textColor = 20
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: Int64 { let o = _accessor.offset(VTOFFSET.id.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var fileId: Int64 { let o = _accessor.offset(VTOFFSET.fileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var title: String! { let o = _accessor.offset(VTOFFSET.title.v); return _accessor.string(at: o) }
  public var titleSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.title.v) }
  public var slug: String! { let o = _accessor.offset(VTOFFSET.slug.v); return _accessor.string(at: o) }
  public var slugSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.slug.v) }
  public var patternFileId: Int64 { let o = _accessor.offset(VTOFFSET.patternFileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var innerColor: Int32 { let o = _accessor.offset(VTOFFSET.innerColor.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var outerColor: Int32 { let o = _accessor.offset(VTOFFSET.outerColor.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var patternColor: Int32 { let o = _accessor.offset(VTOFFSET.patternColor.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var textColor: Int32 { let o = _accessor.offset(VTOFFSET.textColor.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startPeerEmojiStatusContentStarGift(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 9) }
  public static func add(id: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: id, def: 0, at: VTOFFSET.id.p) }
  public static func add(fileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fileId, def: 0, at: VTOFFSET.fileId.p) }
  public static func add(title: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: title, at: VTOFFSET.title.p) }
  public static func add(slug: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: slug, at: VTOFFSET.slug.p) }
  public static func add(patternFileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: patternFileId, def: 0, at: VTOFFSET.patternFileId.p) }
  public static func add(innerColor: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: innerColor, def: 0, at: VTOFFSET.innerColor.p) }
  public static func add(outerColor: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: outerColor, def: 0, at: VTOFFSET.outerColor.p) }
  public static func add(patternColor: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: patternColor, def: 0, at: VTOFFSET.patternColor.p) }
  public static func add(textColor: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: textColor, def: 0, at: VTOFFSET.textColor.p) }
  public static func endPeerEmojiStatusContentStarGift(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [8, 10]); return end }
  public static func createPeerEmojiStatusContentStarGift(
    _ fbb: inout FlatBufferBuilder,
    id: Int64 = 0,
    fileId: Int64 = 0,
    titleOffset title: Offset,
    slugOffset slug: Offset,
    patternFileId: Int64 = 0,
    innerColor: Int32 = 0,
    outerColor: Int32 = 0,
    patternColor: Int32 = 0,
    textColor: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_PeerEmojiStatusContentStarGift.startPeerEmojiStatusContentStarGift(&fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(id: id, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(fileId: fileId, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(title: title, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(slug: slug, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(patternFileId: patternFileId, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(innerColor: innerColor, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(outerColor: outerColor, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(patternColor: patternColor, &fbb)
    TelegramCore_PeerEmojiStatusContentStarGift.add(textColor: textColor, &fbb)
    return TelegramCore_PeerEmojiStatusContentStarGift.endPeerEmojiStatusContentStarGift(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.fileId.p, fieldName: "fileId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.title.p, fieldName: "title", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.slug.p, fieldName: "slug", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.patternFileId.p, fieldName: "patternFileId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.innerColor.p, fieldName: "innerColor", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.outerColor.p, fieldName: "outerColor", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.patternColor.p, fieldName: "patternColor", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.textColor.p, fieldName: "textColor", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct TelegramCore_PeerEmojiStatusContent: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_PeerEmojiStatusContent_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_PeerEmojiStatusContent_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startPeerEmojiStatusContent(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_PeerEmojiStatusContent_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endPeerEmojiStatusContent(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createPeerEmojiStatusContent(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_PeerEmojiStatusContent_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_PeerEmojiStatusContent.startPeerEmojiStatusContent(&fbb)
    TelegramCore_PeerEmojiStatusContent.add(valueType: valueType, &fbb)
    TelegramCore_PeerEmojiStatusContent.add(value: value, &fbb)
    return TelegramCore_PeerEmojiStatusContent.endPeerEmojiStatusContent(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_PeerEmojiStatusContent_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .peeremojistatuscontentemoji:
        try ForwardOffset<TelegramCore_PeerEmojiStatusContentEmoji>.verify(&verifier, at: pos, of: TelegramCore_PeerEmojiStatusContentEmoji.self)
      case .peeremojistatuscontentstargift:
        try ForwardOffset<TelegramCore_PeerEmojiStatusContentStarGift>.verify(&verifier, at: pos, of: TelegramCore_PeerEmojiStatusContentStarGift.self)
      }
    })
    _v.finish()
  }
}

public struct TelegramCore_PeerEmojiStatus: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case content = 4
    case expirationDate = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var content: TelegramCore_PeerEmojiStatusContent! { let o = _accessor.offset(VTOFFSET.content.v); return TelegramCore_PeerEmojiStatusContent(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var expirationDate: Int32 { let o = _accessor.offset(VTOFFSET.expirationDate.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startPeerEmojiStatus(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(content: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: content, at: VTOFFSET.content.p) }
  public static func add(expirationDate: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: expirationDate, def: 0, at: VTOFFSET.expirationDate.p) }
  public static func endPeerEmojiStatus(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createPeerEmojiStatus(
    _ fbb: inout FlatBufferBuilder,
    contentOffset content: Offset,
    expirationDate: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_PeerEmojiStatus.startPeerEmojiStatus(&fbb)
    TelegramCore_PeerEmojiStatus.add(content: content, &fbb)
    TelegramCore_PeerEmojiStatus.add(expirationDate: expirationDate, &fbb)
    return TelegramCore_PeerEmojiStatus.endPeerEmojiStatus(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.content.p, fieldName: "content", required: true, type: ForwardOffset<TelegramCore_PeerEmojiStatusContent>.self)
    try _v.visit(field: VTOFFSET.expirationDate.p, fieldName: "expirationDate", required: false, type: Int32.self)
    _v.finish()
  }
}
