// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_PeerNameColor: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case value = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var value: Int32 { let o = _accessor.offset(VTOFFSET.value.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startPeerNameColor(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(value: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: value, def: 0, at: VTOFFSET.value.p) }
  public static func endPeerNameColor(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createPeerNameColor(
    _ fbb: inout FlatBufferBuilder,
    value: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_PeerNameColor.startPeerNameColor(&fbb)
    TelegramCore_PeerNameColor.add(value: value, &fbb)
    return TelegramCore_PeerNameColor.endPeerNameColor(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.value.p, fieldName: "value", required: false, type: Int32.self)
    _v.finish()
  }
}
