// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_PixelDimensions: NativeStruct, Verifiable, FlatbuffersInitializable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }

  private var _width: Int32
  private var _height: Int32

  public init(_ bb: ByteBuffer, o: Int32) {
    let _accessor = Struct(bb: bb, position: o)
    _width = _accessor.readBuffer(of: Int32.self, at: 0)
    _height = _accessor.readBuffer(of: Int32.self, at: 4)
  }

  public init(width: Int32, height: Int32) {
    _width = width
    _height = height
  }

  public init() {
    _width = 0
    _height = 0
  }

  public var width: Int32 { _width }
  public var height: Int32 { _height }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    try verifier.inBuffer(position: position, of: TelegramCore_PixelDimensions.self)
  }
}

public struct TelegramCore_PixelDimensions_Mutable: FlatBufferObject {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Struct

  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Struct(bb: bb, position: o) }

  public var width: Int32 { return _accessor.readBuffer(of: Int32.self, at: 0) }
  public var height: Int32 { return _accessor.readBuffer(of: Int32.self, at: 4) }
}

