// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_RichText_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case richtextEmpty = 1
  case richtextPlain = 2
  case richtextBold = 3
  case richtextItalic = 4
  case richtextUnderline = 5
  case richtextStrikethrough = 6
  case richtextFixed = 7
  case richtextUrl = 8
  case richtextEmail = 9
  case richtextConcat = 10
  case richtextSubscript = 11
  case richtextSuperscript = 12
  case richtextMarked = 13
  case richtextPhone = 14
  case richtextImage = 15
  case richtextAnchor = 16

  public static var max: TelegramCore_RichText_Value { return .richtextAnchor }
  public static var min: TelegramCore_RichText_Value { return .none_ }
}


public struct TelegramCore_RichText: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_RichText_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_RichText_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startRichText(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_RichText_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endRichText(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createRichText(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_RichText_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText.startRichText(&fbb)
    TelegramCore_RichText.add(valueType: valueType, &fbb)
    TelegramCore_RichText.add(value: value, &fbb)
    return TelegramCore_RichText.endRichText(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_RichText_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .richtextEmpty:
        try ForwardOffset<TelegramCore_RichText_Empty>.verify(&verifier, at: pos, of: TelegramCore_RichText_Empty.self)
      case .richtextPlain:
        try ForwardOffset<TelegramCore_RichText_Plain>.verify(&verifier, at: pos, of: TelegramCore_RichText_Plain.self)
      case .richtextBold:
        try ForwardOffset<TelegramCore_RichText_Bold>.verify(&verifier, at: pos, of: TelegramCore_RichText_Bold.self)
      case .richtextItalic:
        try ForwardOffset<TelegramCore_RichText_Italic>.verify(&verifier, at: pos, of: TelegramCore_RichText_Italic.self)
      case .richtextUnderline:
        try ForwardOffset<TelegramCore_RichText_Underline>.verify(&verifier, at: pos, of: TelegramCore_RichText_Underline.self)
      case .richtextStrikethrough:
        try ForwardOffset<TelegramCore_RichText_Strikethrough>.verify(&verifier, at: pos, of: TelegramCore_RichText_Strikethrough.self)
      case .richtextFixed:
        try ForwardOffset<TelegramCore_RichText_Fixed>.verify(&verifier, at: pos, of: TelegramCore_RichText_Fixed.self)
      case .richtextUrl:
        try ForwardOffset<TelegramCore_RichText_Url>.verify(&verifier, at: pos, of: TelegramCore_RichText_Url.self)
      case .richtextEmail:
        try ForwardOffset<TelegramCore_RichText_Email>.verify(&verifier, at: pos, of: TelegramCore_RichText_Email.self)
      case .richtextConcat:
        try ForwardOffset<TelegramCore_RichText_Concat>.verify(&verifier, at: pos, of: TelegramCore_RichText_Concat.self)
      case .richtextSubscript:
        try ForwardOffset<TelegramCore_RichText_Subscript>.verify(&verifier, at: pos, of: TelegramCore_RichText_Subscript.self)
      case .richtextSuperscript:
        try ForwardOffset<TelegramCore_RichText_Superscript>.verify(&verifier, at: pos, of: TelegramCore_RichText_Superscript.self)
      case .richtextMarked:
        try ForwardOffset<TelegramCore_RichText_Marked>.verify(&verifier, at: pos, of: TelegramCore_RichText_Marked.self)
      case .richtextPhone:
        try ForwardOffset<TelegramCore_RichText_Phone>.verify(&verifier, at: pos, of: TelegramCore_RichText_Phone.self)
      case .richtextImage:
        try ForwardOffset<TelegramCore_RichText_Image>.verify(&verifier, at: pos, of: TelegramCore_RichText_Image.self)
      case .richtextAnchor:
        try ForwardOffset<TelegramCore_RichText_Anchor>.verify(&verifier, at: pos, of: TelegramCore_RichText_Anchor.self)
      }
    })
    _v.finish()
  }
}

public struct TelegramCore_RichText_Empty: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startRichText_Empty(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endRichText_Empty(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Plain: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: String! { let o = _accessor.offset(VTOFFSET.text.v); return _accessor.string(at: o) }
  public var textSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.text.v) }
  public static func startRichText_Plain(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Plain(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Plain(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Plain.startRichText_Plain(&fbb)
    TelegramCore_RichText_Plain.add(text: text, &fbb)
    return TelegramCore_RichText_Plain.endRichText_Plain(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Bold: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Bold(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Bold(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Bold(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Bold.startRichText_Bold(&fbb)
    TelegramCore_RichText_Bold.add(text: text, &fbb)
    return TelegramCore_RichText_Bold.endRichText_Bold(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Italic: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Italic(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Italic(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Italic(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Italic.startRichText_Italic(&fbb)
    TelegramCore_RichText_Italic.add(text: text, &fbb)
    return TelegramCore_RichText_Italic.endRichText_Italic(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Underline: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Underline(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Underline(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Underline(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Underline.startRichText_Underline(&fbb)
    TelegramCore_RichText_Underline.add(text: text, &fbb)
    return TelegramCore_RichText_Underline.endRichText_Underline(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Strikethrough: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Strikethrough(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Strikethrough(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Strikethrough(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Strikethrough.startRichText_Strikethrough(&fbb)
    TelegramCore_RichText_Strikethrough.add(text: text, &fbb)
    return TelegramCore_RichText_Strikethrough.endRichText_Strikethrough(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Fixed: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Fixed(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Fixed(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Fixed(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Fixed.startRichText_Fixed(&fbb)
    TelegramCore_RichText_Fixed.add(text: text, &fbb)
    return TelegramCore_RichText_Fixed.endRichText_Fixed(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Url: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    case url = 6
    case webpageId = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var url: String! { let o = _accessor.offset(VTOFFSET.url.v); return _accessor.string(at: o) }
  public var urlSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.url.v) }
  public var webpageId: TelegramCore_MediaId? { let o = _accessor.offset(VTOFFSET.webpageId.v); return o == 0 ? nil : _accessor.readBuffer(of: TelegramCore_MediaId.self, at: o) }
  public var mutableWebpageId: TelegramCore_MediaId_Mutable? { let o = _accessor.offset(VTOFFSET.webpageId.v); return o == 0 ? nil : TelegramCore_MediaId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public static func startRichText_Url(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func add(url: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: url, at: VTOFFSET.url.p) }
  public static func add(webpageId: TelegramCore_MediaId?, _ fbb: inout FlatBufferBuilder) { guard let webpageId = webpageId else { return }; fbb.create(struct: webpageId, position: VTOFFSET.webpageId.p) }
  public static func endRichText_Url(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6]); return end }
  public static func createRichText_Url(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset,
    urlOffset url: Offset,
    webpageId: TelegramCore_MediaId? = nil
  ) -> Offset {
    let __start = TelegramCore_RichText_Url.startRichText_Url(&fbb)
    TelegramCore_RichText_Url.add(text: text, &fbb)
    TelegramCore_RichText_Url.add(url: url, &fbb)
    TelegramCore_RichText_Url.add(webpageId: webpageId, &fbb)
    return TelegramCore_RichText_Url.endRichText_Url(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    try _v.visit(field: VTOFFSET.url.p, fieldName: "url", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.webpageId.p, fieldName: "webpageId", required: false, type: TelegramCore_MediaId.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Email: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    case email = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var email: String! { let o = _accessor.offset(VTOFFSET.email.v); return _accessor.string(at: o) }
  public var emailSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.email.v) }
  public static func startRichText_Email(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func add(email: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: email, at: VTOFFSET.email.p) }
  public static func endRichText_Email(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6]); return end }
  public static func createRichText_Email(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset,
    emailOffset email: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Email.startRichText_Email(&fbb)
    TelegramCore_RichText_Email.add(text: text, &fbb)
    TelegramCore_RichText_Email.add(email: email, &fbb)
    return TelegramCore_RichText_Email.endRichText_Email(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    try _v.visit(field: VTOFFSET.email.p, fieldName: "email", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Concat: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case texts = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var hasTexts: Bool { let o = _accessor.offset(VTOFFSET.texts.v); return o == 0 ? false : true }
  public var textsCount: Int32 { let o = _accessor.offset(VTOFFSET.texts.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func texts(at index: Int32) -> TelegramCore_RichText? { let o = _accessor.offset(VTOFFSET.texts.v); return o == 0 ? nil : TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public static func startRichText_Concat(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func addVectorOf(texts: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: texts, at: VTOFFSET.texts.p) }
  public static func endRichText_Concat(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Concat(
    _ fbb: inout FlatBufferBuilder,
    textsVectorOffset texts: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Concat.startRichText_Concat(&fbb)
    TelegramCore_RichText_Concat.addVectorOf(texts: texts, &fbb)
    return TelegramCore_RichText_Concat.endRichText_Concat(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.texts.p, fieldName: "texts", required: true, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_RichText>, TelegramCore_RichText>>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Subscript: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Subscript(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Subscript(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Subscript(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Subscript.startRichText_Subscript(&fbb)
    TelegramCore_RichText_Subscript.add(text: text, &fbb)
    return TelegramCore_RichText_Subscript.endRichText_Subscript(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Superscript: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Superscript(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Superscript(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Superscript(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Superscript.startRichText_Superscript(&fbb)
    TelegramCore_RichText_Superscript.add(text: text, &fbb)
    return TelegramCore_RichText_Superscript.endRichText_Superscript(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Marked: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startRichText_Marked(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func endRichText_Marked(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createRichText_Marked(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Marked.startRichText_Marked(&fbb)
    TelegramCore_RichText_Marked.add(text: text, &fbb)
    return TelegramCore_RichText_Marked.endRichText_Marked(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Phone: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    case phone = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var phone: String! { let o = _accessor.offset(VTOFFSET.phone.v); return _accessor.string(at: o) }
  public var phoneSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.phone.v) }
  public static func startRichText_Phone(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func add(phone: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: phone, at: VTOFFSET.phone.p) }
  public static func endRichText_Phone(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6]); return end }
  public static func createRichText_Phone(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset,
    phoneOffset phone: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Phone.startRichText_Phone(&fbb)
    TelegramCore_RichText_Phone.add(text: text, &fbb)
    TelegramCore_RichText_Phone.add(phone: phone, &fbb)
    return TelegramCore_RichText_Phone.endRichText_Phone(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    try _v.visit(field: VTOFFSET.phone.p, fieldName: "phone", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Image: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case dimensions = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: TelegramCore_MediaId! { let o = _accessor.offset(VTOFFSET.id.v); return _accessor.readBuffer(of: TelegramCore_MediaId.self, at: o) }
  public var mutableId: TelegramCore_MediaId_Mutable! { let o = _accessor.offset(VTOFFSET.id.v); return TelegramCore_MediaId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var dimensions: TelegramCore_PixelDimensions! { let o = _accessor.offset(VTOFFSET.dimensions.v); return _accessor.readBuffer(of: TelegramCore_PixelDimensions.self, at: o) }
  public var mutableDimensions: TelegramCore_PixelDimensions_Mutable! { let o = _accessor.offset(VTOFFSET.dimensions.v); return TelegramCore_PixelDimensions_Mutable(_accessor.bb, o: o + _accessor.position) }
  public static func startRichText_Image(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(id: TelegramCore_MediaId?, _ fbb: inout FlatBufferBuilder) { guard let id = id else { return }; fbb.create(struct: id, position: VTOFFSET.id.p) }
  public static func add(dimensions: TelegramCore_PixelDimensions?, _ fbb: inout FlatBufferBuilder) { guard let dimensions = dimensions else { return }; fbb.create(struct: dimensions, position: VTOFFSET.dimensions.p) }
  public static func endRichText_Image(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6]); return end }
  public static func createRichText_Image(
    _ fbb: inout FlatBufferBuilder,
    id: TelegramCore_MediaId,
    dimensions: TelegramCore_PixelDimensions
  ) -> Offset {
    let __start = TelegramCore_RichText_Image.startRichText_Image(&fbb)
    TelegramCore_RichText_Image.add(id: id, &fbb)
    TelegramCore_RichText_Image.add(dimensions: dimensions, &fbb)
    return TelegramCore_RichText_Image.endRichText_Image(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: true, type: TelegramCore_MediaId.self)
    try _v.visit(field: VTOFFSET.dimensions.p, fieldName: "dimensions", required: true, type: TelegramCore_PixelDimensions.self)
    _v.finish()
  }
}

public struct TelegramCore_RichText_Anchor: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case text = 4
    case name = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var text: TelegramCore_RichText! { let o = _accessor.offset(VTOFFSET.text.v); return TelegramCore_RichText(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var name: String! { let o = _accessor.offset(VTOFFSET.name.v); return _accessor.string(at: o) }
  public var nameSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.name.v) }
  public static func startRichText_Anchor(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: text, at: VTOFFSET.text.p) }
  public static func add(name: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: name, at: VTOFFSET.name.p) }
  public static func endRichText_Anchor(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6]); return end }
  public static func createRichText_Anchor(
    _ fbb: inout FlatBufferBuilder,
    textOffset text: Offset,
    nameOffset name: Offset
  ) -> Offset {
    let __start = TelegramCore_RichText_Anchor.startRichText_Anchor(&fbb)
    TelegramCore_RichText_Anchor.add(text: text, &fbb)
    TelegramCore_RichText_Anchor.add(name: name, &fbb)
    return TelegramCore_RichText_Anchor.endRichText_Anchor(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.text.p, fieldName: "text", required: true, type: ForwardOffset<TelegramCore_RichText>.self)
    try _v.visit(field: VTOFFSET.name.p, fieldName: "name", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

