// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_StarsAmount: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case value = 4
    case nanos = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var value: Int64 { let o = _accessor.offset(VTOFFSET.value.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var nanos: Int32 { let o = _accessor.offset(VTOFFSET.nanos.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startStarsAmount(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(value: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: value, def: 0, at: VTOFFSET.value.p) }
  public static func add(nanos: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: nanos, def: 0, at: VTOFFSET.nanos.p) }
  public static func endStarsAmount(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createStarsAmount(
    _ fbb: inout FlatBufferBuilder,
    value: Int64 = 0,
    nanos: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_StarsAmount.startStarsAmount(&fbb)
    TelegramCore_StarsAmount.add(value: value, &fbb)
    TelegramCore_StarsAmount.add(nanos: nanos, &fbb)
    return TelegramCore_StarsAmount.endStarsAmount(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.value.p, fieldName: "value", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.nanos.p, fieldName: "nanos", required: false, type: Int32.self)
    _v.finish()
  }
}

