// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_StickerPackReference_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case stickerpackreferenceId = 1
  case stickerpackreferenceName = 2
  case stickerpackreferenceAnimatedemoji = 3
  case stickerpackreferenceDice = 4
  case stickerpackreferenceAnimatedemojianimations = 5
  case stickerpackreferencePremiumgifts = 6
  case stickerpackreferenceEmojigenericanimations = 7
  case stickerpackreferenceIconstatusemoji = 8
  case stickerpackreferenceIcontopicemoji = 9
  case stickerpackreferenceIconchannelstatusemoji = 10
  case stickerpackreferenceTongifts = 11

  public static var max: TelegramCore_StickerPackReference_Value { return .stickerpackreferenceTongifts }
  public static var min: TelegramCore_StickerPackReference_Value { return .none_ }
}


public struct TelegramCore_StickerPackReference_Id: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case accessHash = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: Int64 { let o = _accessor.offset(VTOFFSET.id.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startStickerPackReference_Id(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(id: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: id, def: 0, at: VTOFFSET.id.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func endStickerPackReference_Id(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createStickerPackReference_Id(
    _ fbb: inout FlatBufferBuilder,
    id: Int64 = 0,
    accessHash: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_StickerPackReference_Id.startStickerPackReference_Id(&fbb)
    TelegramCore_StickerPackReference_Id.add(id: id, &fbb)
    TelegramCore_StickerPackReference_Id.add(accessHash: accessHash, &fbb)
    return TelegramCore_StickerPackReference_Id.endStickerPackReference_Id(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_Name: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case name = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var name: String! { let o = _accessor.offset(VTOFFSET.name.v); return _accessor.string(at: o) }
  public var nameSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.name.v) }
  public static func startStickerPackReference_Name(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(name: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: name, at: VTOFFSET.name.p) }
  public static func endStickerPackReference_Name(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createStickerPackReference_Name(
    _ fbb: inout FlatBufferBuilder,
    nameOffset name: Offset
  ) -> Offset {
    let __start = TelegramCore_StickerPackReference_Name.startStickerPackReference_Name(&fbb)
    TelegramCore_StickerPackReference_Name.add(name: name, &fbb)
    return TelegramCore_StickerPackReference_Name.endStickerPackReference_Name(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.name.p, fieldName: "name", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_AnimatedEmoji: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_AnimatedEmoji(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_AnimatedEmoji(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_Dice: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case emoji = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var emoji: String! { let o = _accessor.offset(VTOFFSET.emoji.v); return _accessor.string(at: o) }
  public var emojiSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.emoji.v) }
  public static func startStickerPackReference_Dice(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(emoji: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: emoji, at: VTOFFSET.emoji.p) }
  public static func endStickerPackReference_Dice(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createStickerPackReference_Dice(
    _ fbb: inout FlatBufferBuilder,
    emojiOffset emoji: Offset
  ) -> Offset {
    let __start = TelegramCore_StickerPackReference_Dice.startStickerPackReference_Dice(&fbb)
    TelegramCore_StickerPackReference_Dice.add(emoji: emoji, &fbb)
    return TelegramCore_StickerPackReference_Dice.endStickerPackReference_Dice(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.emoji.p, fieldName: "emoji", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_AnimatedEmojiAnimations: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_AnimatedEmojiAnimations(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_AnimatedEmojiAnimations(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_PremiumGifts: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_PremiumGifts(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_PremiumGifts(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_EmojiGenericAnimations: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_EmojiGenericAnimations(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_EmojiGenericAnimations(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_IconStatusEmoji: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_IconStatusEmoji(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_IconStatusEmoji(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_IconTopicEmoji: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_IconTopicEmoji(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_IconTopicEmoji(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_IconChannelStatusEmoji: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_IconChannelStatusEmoji(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_IconChannelStatusEmoji(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference_TonGifts: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startStickerPackReference_TonGifts(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endStickerPackReference_TonGifts(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_StickerPackReference: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_StickerPackReference_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_StickerPackReference_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startStickerPackReference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_StickerPackReference_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endStickerPackReference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createStickerPackReference(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_StickerPackReference_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_StickerPackReference.startStickerPackReference(&fbb)
    TelegramCore_StickerPackReference.add(valueType: valueType, &fbb)
    TelegramCore_StickerPackReference.add(value: value, &fbb)
    return TelegramCore_StickerPackReference.endStickerPackReference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_StickerPackReference_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .stickerpackreferenceId:
        try ForwardOffset<TelegramCore_StickerPackReference_Id>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_Id.self)
      case .stickerpackreferenceName:
        try ForwardOffset<TelegramCore_StickerPackReference_Name>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_Name.self)
      case .stickerpackreferenceAnimatedemoji:
        try ForwardOffset<TelegramCore_StickerPackReference_AnimatedEmoji>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_AnimatedEmoji.self)
      case .stickerpackreferenceDice:
        try ForwardOffset<TelegramCore_StickerPackReference_Dice>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_Dice.self)
      case .stickerpackreferenceAnimatedemojianimations:
        try ForwardOffset<TelegramCore_StickerPackReference_AnimatedEmojiAnimations>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_AnimatedEmojiAnimations.self)
      case .stickerpackreferencePremiumgifts:
        try ForwardOffset<TelegramCore_StickerPackReference_PremiumGifts>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_PremiumGifts.self)
      case .stickerpackreferenceEmojigenericanimations:
        try ForwardOffset<TelegramCore_StickerPackReference_EmojiGenericAnimations>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_EmojiGenericAnimations.self)
      case .stickerpackreferenceIconstatusemoji:
        try ForwardOffset<TelegramCore_StickerPackReference_IconStatusEmoji>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_IconStatusEmoji.self)
      case .stickerpackreferenceIcontopicemoji:
        try ForwardOffset<TelegramCore_StickerPackReference_IconTopicEmoji>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_IconTopicEmoji.self)
      case .stickerpackreferenceIconchannelstatusemoji:
        try ForwardOffset<TelegramCore_StickerPackReference_IconChannelStatusEmoji>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_IconChannelStatusEmoji.self)
      case .stickerpackreferenceTongifts:
        try ForwardOffset<TelegramCore_StickerPackReference_TonGifts>.verify(&verifier, at: pos, of: TelegramCore_StickerPackReference_TonGifts.self)
      }
    })
    _v.finish()
  }
}

