// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_StickerPackCollectionInfo: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case flags = 6
    case accessHash = 8
    case title = 10
    case shortName = 12
    case thumbnail = 14
    case thumbnailFileId = 16
    case immediateThumbnailData = 18
    case hash = 20
    case count = 22
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: TelegramCore_ItemCollectionId! { let o = _accessor.offset(VTOFFSET.id.v); return _accessor.readBuffer(of: TelegramCore_ItemCollectionId.self, at: o) }
  public var mutableId: TelegramCore_ItemCollectionId_Mutable! { let o = _accessor.offset(VTOFFSET.id.v); return TelegramCore_ItemCollectionId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var title: String! { let o = _accessor.offset(VTOFFSET.title.v); return _accessor.string(at: o) }
  public var titleSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.title.v) }
  public var shortName: String! { let o = _accessor.offset(VTOFFSET.shortName.v); return _accessor.string(at: o) }
  public var shortNameSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.shortName.v) }
  public var thumbnail: TelegramCore_TelegramMediaImageRepresentation? { let o = _accessor.offset(VTOFFSET.thumbnail.v); return o == 0 ? nil : TelegramCore_TelegramMediaImageRepresentation(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var thumbnailFileId: Int64 { let o = _accessor.offset(VTOFFSET.thumbnailFileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var hasImmediateThumbnailData: Bool { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? false : true }
  public var immediateThumbnailDataCount: Int32 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func immediateThumbnailData(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var immediateThumbnailData: [UInt8] { return _accessor.getVector(at: VTOFFSET.immediateThumbnailData.v) ?? [] }
  public var hash: Int32 { let o = _accessor.offset(VTOFFSET.hash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var count: Int32 { let o = _accessor.offset(VTOFFSET.count.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startStickerPackCollectionInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 10) }
  public static func add(id: TelegramCore_ItemCollectionId?, _ fbb: inout FlatBufferBuilder) { guard let id = id else { return }; fbb.create(struct: id, position: VTOFFSET.id.p) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func add(title: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: title, at: VTOFFSET.title.p) }
  public static func add(shortName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: shortName, at: VTOFFSET.shortName.p) }
  public static func add(thumbnail: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: thumbnail, at: VTOFFSET.thumbnail.p) }
  public static func add(thumbnailFileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: thumbnailFileId, def: 0, at: VTOFFSET.thumbnailFileId.p) }
  public static func addVectorOf(immediateThumbnailData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: immediateThumbnailData, at: VTOFFSET.immediateThumbnailData.p) }
  public static func add(hash: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hash, def: 0, at: VTOFFSET.hash.p) }
  public static func add(count: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: count, def: 0, at: VTOFFSET.count.p) }
  public static func endStickerPackCollectionInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 10, 12]); return end }
  public static func createStickerPackCollectionInfo(
    _ fbb: inout FlatBufferBuilder,
    id: TelegramCore_ItemCollectionId,
    flags: Int32 = 0,
    accessHash: Int64 = 0,
    titleOffset title: Offset,
    shortNameOffset shortName: Offset,
    thumbnailOffset thumbnail: Offset = Offset(),
    thumbnailFileId: Int64 = 0,
    immediateThumbnailDataVectorOffset immediateThumbnailData: Offset = Offset(),
    hash: Int32 = 0,
    count: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_StickerPackCollectionInfo.startStickerPackCollectionInfo(&fbb)
    TelegramCore_StickerPackCollectionInfo.add(id: id, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(flags: flags, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(accessHash: accessHash, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(title: title, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(shortName: shortName, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(thumbnail: thumbnail, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(thumbnailFileId: thumbnailFileId, &fbb)
    TelegramCore_StickerPackCollectionInfo.addVectorOf(immediateThumbnailData: immediateThumbnailData, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(hash: hash, &fbb)
    TelegramCore_StickerPackCollectionInfo.add(count: count, &fbb)
    return TelegramCore_StickerPackCollectionInfo.endStickerPackCollectionInfo(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: true, type: TelegramCore_ItemCollectionId.self)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.title.p, fieldName: "title", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.shortName.p, fieldName: "shortName", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.thumbnail.p, fieldName: "thumbnail", required: false, type: ForwardOffset<TelegramCore_TelegramMediaImageRepresentation>.self)
    try _v.visit(field: VTOFFSET.thumbnailFileId.p, fieldName: "thumbnailFileId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.immediateThumbnailData.p, fieldName: "immediateThumbnailData", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.hash.p, fieldName: "hash", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.count.p, fieldName: "count", required: false, type: Int32.self)
    _v.finish()
  }
}

