// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_DeviceContactPhoneNumberData: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case label = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var label: String! { let o = _accessor.offset(VTOFFSET.label.v); return _accessor.string(at: o) }
  public var labelSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.label.v) }
  public var value: String! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.string(at: o) }
  public var valueSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.value.v) }
  public static func startDeviceContactPhoneNumberData(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(label: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: label, at: VTOFFSET.label.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endDeviceContactPhoneNumberData(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6]); return end }
  public static func createDeviceContactPhoneNumberData(
    _ fbb: inout FlatBufferBuilder,
    labelOffset label: Offset,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_DeviceContactPhoneNumberData.startDeviceContactPhoneNumberData(&fbb)
    TelegramCore_DeviceContactPhoneNumberData.add(label: label, &fbb)
    TelegramCore_DeviceContactPhoneNumberData.add(value: value, &fbb)
    return TelegramCore_DeviceContactPhoneNumberData.endDeviceContactPhoneNumberData(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.label.p, fieldName: "label", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.value.p, fieldName: "value", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_StoredDeviceContactData: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case firstName = 4
    case lastName = 6
    case phoneNumbers = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var firstName: String! { let o = _accessor.offset(VTOFFSET.firstName.v); return _accessor.string(at: o) }
  public var firstNameSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.firstName.v) }
  public var lastName: String! { let o = _accessor.offset(VTOFFSET.lastName.v); return _accessor.string(at: o) }
  public var lastNameSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.lastName.v) }
  public var hasPhoneNumbers: Bool { let o = _accessor.offset(VTOFFSET.phoneNumbers.v); return o == 0 ? false : true }
  public var phoneNumbersCount: Int32 { let o = _accessor.offset(VTOFFSET.phoneNumbers.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func phoneNumbers(at index: Int32) -> TelegramCore_DeviceContactPhoneNumberData? { let o = _accessor.offset(VTOFFSET.phoneNumbers.v); return o == 0 ? nil : TelegramCore_DeviceContactPhoneNumberData(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public static func startStoredDeviceContactData(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(firstName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: firstName, at: VTOFFSET.firstName.p) }
  public static func add(lastName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: lastName, at: VTOFFSET.lastName.p) }
  public static func addVectorOf(phoneNumbers: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: phoneNumbers, at: VTOFFSET.phoneNumbers.p) }
  public static func endStoredDeviceContactData(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6]); return end }
  public static func createStoredDeviceContactData(
    _ fbb: inout FlatBufferBuilder,
    firstNameOffset firstName: Offset,
    lastNameOffset lastName: Offset,
    phoneNumbersVectorOffset phoneNumbers: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_StoredDeviceContactData.startStoredDeviceContactData(&fbb)
    TelegramCore_StoredDeviceContactData.add(firstName: firstName, &fbb)
    TelegramCore_StoredDeviceContactData.add(lastName: lastName, &fbb)
    TelegramCore_StoredDeviceContactData.addVectorOf(phoneNumbers: phoneNumbers, &fbb)
    return TelegramCore_StoredDeviceContactData.endStoredDeviceContactData(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.firstName.p, fieldName: "firstName", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.lastName.p, fieldName: "lastName", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.phoneNumbers.p, fieldName: "phoneNumbers", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_DeviceContactPhoneNumberData>, TelegramCore_DeviceContactPhoneNumberData>>.self)
    _v.finish()
  }
}

