// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_TelegramChannelInfo_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case telegramchannelinfoBroadcast = 1
  case telegramchannelinfoGroup = 2

  public static var max: TelegramCore_TelegramChannelInfo_Value { return .telegramchannelinfoGroup }
  public static var min: TelegramCore_TelegramChannelInfo_Value { return .none_ }
}


public struct TelegramCore_TelegramChannelInfo_Broadcast: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case flags = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramChannelInfo_Broadcast(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func endTelegramChannelInfo_Broadcast(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramChannelInfo_Broadcast(
    _ fbb: inout FlatBufferBuilder,
    flags: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramChannelInfo_Broadcast.startTelegramChannelInfo_Broadcast(&fbb)
    TelegramCore_TelegramChannelInfo_Broadcast.add(flags: flags, &fbb)
    return TelegramCore_TelegramChannelInfo_Broadcast.endTelegramChannelInfo_Broadcast(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramChannelInfo_Group: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case flags = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramChannelInfo_Group(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func endTelegramChannelInfo_Group(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramChannelInfo_Group(
    _ fbb: inout FlatBufferBuilder,
    flags: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramChannelInfo_Group.startTelegramChannelInfo_Group(&fbb)
    TelegramCore_TelegramChannelInfo_Group.add(flags: flags, &fbb)
    return TelegramCore_TelegramChannelInfo_Group.endTelegramChannelInfo_Group(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramChannelInfo: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_TelegramChannelInfo_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_TelegramChannelInfo_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startTelegramChannelInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_TelegramChannelInfo_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endTelegramChannelInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createTelegramChannelInfo(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_TelegramChannelInfo_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_TelegramChannelInfo.startTelegramChannelInfo(&fbb)
    TelegramCore_TelegramChannelInfo.add(valueType: valueType, &fbb)
    TelegramCore_TelegramChannelInfo.add(value: value, &fbb)
    return TelegramCore_TelegramChannelInfo.endTelegramChannelInfo(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_TelegramChannelInfo_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .telegramchannelinfoBroadcast:
        try ForwardOffset<TelegramCore_TelegramChannelInfo_Broadcast>.verify(&verifier, at: pos, of: TelegramCore_TelegramChannelInfo_Broadcast.self)
      case .telegramchannelinfoGroup:
        try ForwardOffset<TelegramCore_TelegramChannelInfo_Group>.verify(&verifier, at: pos, of: TelegramCore_TelegramChannelInfo_Group.self)
      }
    })
    _v.finish()
  }
}

public struct TelegramCore_TelegramChannel: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case accessHash = 6
    case title = 8
    case username = 10
    case photo = 12
    case creationDate = 14
    case version = 16
    case participationStatus = 18
    case info = 20
    case flags = 22
    case restrictionInfo = 24
    case adminRights = 26
    case bannedRights = 28
    case defaultBannedRights = 30
    case usernames = 32
    case storiesHidden = 34
    case nameColor = 36
    case backgroundEmojiId = 38
    case profileColor = 40
    case profileBackgroundEmojiId = 42
    case emojiStatus = 44
    case approximateBoostLevel = 46
    case subscriptionUntilDate = 48
    case verificationIconFileId = 50
    case sendPaidMessageStars = 52
    case linkedMonoforumId = 54
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: TelegramCore_PeerId! { let o = _accessor.offset(VTOFFSET.id.v); return _accessor.readBuffer(of: TelegramCore_PeerId.self, at: o) }
  public var mutableId: TelegramCore_PeerId_Mutable! { let o = _accessor.offset(VTOFFSET.id.v); return TelegramCore_PeerId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var accessHash: TelegramCore_TelegramPeerAccessHash? { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? nil : TelegramCore_TelegramPeerAccessHash(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var title: String! { let o = _accessor.offset(VTOFFSET.title.v); return _accessor.string(at: o) }
  public var titleSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.title.v) }
  public var username: String? { let o = _accessor.offset(VTOFFSET.username.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var usernameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.username.v) }
  public var hasPhoto: Bool { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? false : true }
  public var photoCount: Int32 { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func photo(at index: Int32) -> TelegramCore_TelegramMediaImageRepresentation? { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? nil : TelegramCore_TelegramMediaImageRepresentation(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var creationDate: Int32 { let o = _accessor.offset(VTOFFSET.creationDate.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var version: Int32 { let o = _accessor.offset(VTOFFSET.version.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var participationStatus: Int32 { let o = _accessor.offset(VTOFFSET.participationStatus.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var info: TelegramCore_TelegramChannelInfo! { let o = _accessor.offset(VTOFFSET.info.v); return TelegramCore_TelegramChannelInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var restrictionInfo: TelegramCore_PeerAccessRestrictionInfo? { let o = _accessor.offset(VTOFFSET.restrictionInfo.v); return o == 0 ? nil : TelegramCore_PeerAccessRestrictionInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var adminRights: TelegramCore_TelegramChatAdminRights? { let o = _accessor.offset(VTOFFSET.adminRights.v); return o == 0 ? nil : TelegramCore_TelegramChatAdminRights(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var bannedRights: TelegramCore_TelegramChatBannedRights? { let o = _accessor.offset(VTOFFSET.bannedRights.v); return o == 0 ? nil : TelegramCore_TelegramChatBannedRights(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var defaultBannedRights: TelegramCore_TelegramChatBannedRights? { let o = _accessor.offset(VTOFFSET.defaultBannedRights.v); return o == 0 ? nil : TelegramCore_TelegramChatBannedRights(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasUsernames: Bool { let o = _accessor.offset(VTOFFSET.usernames.v); return o == 0 ? false : true }
  public var usernamesCount: Int32 { let o = _accessor.offset(VTOFFSET.usernames.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func usernames(at index: Int32) -> TelegramCore_TelegramPeerUsername? { let o = _accessor.offset(VTOFFSET.usernames.v); return o == 0 ? nil : TelegramCore_TelegramPeerUsername(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var storiesHidden: TelegramCore_OptionalBool? { let o = _accessor.offset(VTOFFSET.storiesHidden.v); return o == 0 ? nil : _accessor.readBuffer(of: TelegramCore_OptionalBool.self, at: o) }
  public var mutableStoriesHidden: TelegramCore_OptionalBool_Mutable? { let o = _accessor.offset(VTOFFSET.storiesHidden.v); return o == 0 ? nil : TelegramCore_OptionalBool_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var nameColor: TelegramCore_PeerNameColor? { let o = _accessor.offset(VTOFFSET.nameColor.v); return o == 0 ? nil : TelegramCore_PeerNameColor(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var backgroundEmojiId: Int64 { let o = _accessor.offset(VTOFFSET.backgroundEmojiId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var profileColor: TelegramCore_PeerNameColor? { let o = _accessor.offset(VTOFFSET.profileColor.v); return o == 0 ? nil : TelegramCore_PeerNameColor(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var profileBackgroundEmojiId: Int64 { let o = _accessor.offset(VTOFFSET.profileBackgroundEmojiId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var emojiStatus: TelegramCore_PeerEmojiStatus? { let o = _accessor.offset(VTOFFSET.emojiStatus.v); return o == 0 ? nil : TelegramCore_PeerEmojiStatus(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var approximateBoostLevel: Int32 { let o = _accessor.offset(VTOFFSET.approximateBoostLevel.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var subscriptionUntilDate: Int32 { let o = _accessor.offset(VTOFFSET.subscriptionUntilDate.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var verificationIconFileId: Int64 { let o = _accessor.offset(VTOFFSET.verificationIconFileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var sendPaidMessageStars: TelegramCore_StarsAmount? { let o = _accessor.offset(VTOFFSET.sendPaidMessageStars.v); return o == 0 ? nil : TelegramCore_StarsAmount(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var linkedMonoforumId: TelegramCore_PeerId? { let o = _accessor.offset(VTOFFSET.linkedMonoforumId.v); return o == 0 ? nil : _accessor.readBuffer(of: TelegramCore_PeerId.self, at: o) }
  public var mutableLinkedMonoforumId: TelegramCore_PeerId_Mutable? { let o = _accessor.offset(VTOFFSET.linkedMonoforumId.v); return o == 0 ? nil : TelegramCore_PeerId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public static func startTelegramChannel(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 26) }
  public static func add(id: TelegramCore_PeerId?, _ fbb: inout FlatBufferBuilder) { guard let id = id else { return }; fbb.create(struct: id, position: VTOFFSET.id.p) }
  public static func add(accessHash: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: accessHash, at: VTOFFSET.accessHash.p) }
  public static func add(title: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: title, at: VTOFFSET.title.p) }
  public static func add(username: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: username, at: VTOFFSET.username.p) }
  public static func addVectorOf(photo: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: photo, at: VTOFFSET.photo.p) }
  public static func add(creationDate: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: creationDate, def: 0, at: VTOFFSET.creationDate.p) }
  public static func add(version: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: version, def: 0, at: VTOFFSET.version.p) }
  public static func add(participationStatus: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: participationStatus, def: 0, at: VTOFFSET.participationStatus.p) }
  public static func add(info: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: info, at: VTOFFSET.info.p) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func add(restrictionInfo: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: restrictionInfo, at: VTOFFSET.restrictionInfo.p) }
  public static func add(adminRights: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: adminRights, at: VTOFFSET.adminRights.p) }
  public static func add(bannedRights: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: bannedRights, at: VTOFFSET.bannedRights.p) }
  public static func add(defaultBannedRights: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: defaultBannedRights, at: VTOFFSET.defaultBannedRights.p) }
  public static func addVectorOf(usernames: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: usernames, at: VTOFFSET.usernames.p) }
  public static func add(storiesHidden: TelegramCore_OptionalBool?, _ fbb: inout FlatBufferBuilder) { guard let storiesHidden = storiesHidden else { return }; fbb.create(struct: storiesHidden, position: VTOFFSET.storiesHidden.p) }
  public static func add(nameColor: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: nameColor, at: VTOFFSET.nameColor.p) }
  public static func add(backgroundEmojiId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: backgroundEmojiId, def: 0, at: VTOFFSET.backgroundEmojiId.p) }
  public static func add(profileColor: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: profileColor, at: VTOFFSET.profileColor.p) }
  public static func add(profileBackgroundEmojiId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: profileBackgroundEmojiId, def: 0, at: VTOFFSET.profileBackgroundEmojiId.p) }
  public static func add(emojiStatus: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: emojiStatus, at: VTOFFSET.emojiStatus.p) }
  public static func add(approximateBoostLevel: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: approximateBoostLevel, def: 0, at: VTOFFSET.approximateBoostLevel.p) }
  public static func add(subscriptionUntilDate: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: subscriptionUntilDate, def: 0, at: VTOFFSET.subscriptionUntilDate.p) }
  public static func add(verificationIconFileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: verificationIconFileId, def: 0, at: VTOFFSET.verificationIconFileId.p) }
  public static func add(sendPaidMessageStars: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sendPaidMessageStars, at: VTOFFSET.sendPaidMessageStars.p) }
  public static func add(linkedMonoforumId: TelegramCore_PeerId?, _ fbb: inout FlatBufferBuilder) { guard let linkedMonoforumId = linkedMonoforumId else { return }; fbb.create(struct: linkedMonoforumId, position: VTOFFSET.linkedMonoforumId.p) }
  public static func endTelegramChannel(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 8, 20]); return end }
  public static func createTelegramChannel(
    _ fbb: inout FlatBufferBuilder,
    id: TelegramCore_PeerId,
    accessHashOffset accessHash: Offset = Offset(),
    titleOffset title: Offset,
    usernameOffset username: Offset = Offset(),
    photoVectorOffset photo: Offset = Offset(),
    creationDate: Int32 = 0,
    version: Int32 = 0,
    participationStatus: Int32 = 0,
    infoOffset info: Offset,
    flags: Int32 = 0,
    restrictionInfoOffset restrictionInfo: Offset = Offset(),
    adminRightsOffset adminRights: Offset = Offset(),
    bannedRightsOffset bannedRights: Offset = Offset(),
    defaultBannedRightsOffset defaultBannedRights: Offset = Offset(),
    usernamesVectorOffset usernames: Offset = Offset(),
    storiesHidden: TelegramCore_OptionalBool? = nil,
    nameColorOffset nameColor: Offset = Offset(),
    backgroundEmojiId: Int64 = 0,
    profileColorOffset profileColor: Offset = Offset(),
    profileBackgroundEmojiId: Int64 = 0,
    emojiStatusOffset emojiStatus: Offset = Offset(),
    approximateBoostLevel: Int32 = 0,
    subscriptionUntilDate: Int32 = 0,
    verificationIconFileId: Int64 = 0,
    sendPaidMessageStarsOffset sendPaidMessageStars: Offset = Offset(),
    linkedMonoforumId: TelegramCore_PeerId? = nil
  ) -> Offset {
    let __start = TelegramCore_TelegramChannel.startTelegramChannel(&fbb)
    TelegramCore_TelegramChannel.add(id: id, &fbb)
    TelegramCore_TelegramChannel.add(accessHash: accessHash, &fbb)
    TelegramCore_TelegramChannel.add(title: title, &fbb)
    TelegramCore_TelegramChannel.add(username: username, &fbb)
    TelegramCore_TelegramChannel.addVectorOf(photo: photo, &fbb)
    TelegramCore_TelegramChannel.add(creationDate: creationDate, &fbb)
    TelegramCore_TelegramChannel.add(version: version, &fbb)
    TelegramCore_TelegramChannel.add(participationStatus: participationStatus, &fbb)
    TelegramCore_TelegramChannel.add(info: info, &fbb)
    TelegramCore_TelegramChannel.add(flags: flags, &fbb)
    TelegramCore_TelegramChannel.add(restrictionInfo: restrictionInfo, &fbb)
    TelegramCore_TelegramChannel.add(adminRights: adminRights, &fbb)
    TelegramCore_TelegramChannel.add(bannedRights: bannedRights, &fbb)
    TelegramCore_TelegramChannel.add(defaultBannedRights: defaultBannedRights, &fbb)
    TelegramCore_TelegramChannel.addVectorOf(usernames: usernames, &fbb)
    TelegramCore_TelegramChannel.add(storiesHidden: storiesHidden, &fbb)
    TelegramCore_TelegramChannel.add(nameColor: nameColor, &fbb)
    TelegramCore_TelegramChannel.add(backgroundEmojiId: backgroundEmojiId, &fbb)
    TelegramCore_TelegramChannel.add(profileColor: profileColor, &fbb)
    TelegramCore_TelegramChannel.add(profileBackgroundEmojiId: profileBackgroundEmojiId, &fbb)
    TelegramCore_TelegramChannel.add(emojiStatus: emojiStatus, &fbb)
    TelegramCore_TelegramChannel.add(approximateBoostLevel: approximateBoostLevel, &fbb)
    TelegramCore_TelegramChannel.add(subscriptionUntilDate: subscriptionUntilDate, &fbb)
    TelegramCore_TelegramChannel.add(verificationIconFileId: verificationIconFileId, &fbb)
    TelegramCore_TelegramChannel.add(sendPaidMessageStars: sendPaidMessageStars, &fbb)
    TelegramCore_TelegramChannel.add(linkedMonoforumId: linkedMonoforumId, &fbb)
    return TelegramCore_TelegramChannel.endTelegramChannel(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: true, type: TelegramCore_PeerId.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: ForwardOffset<TelegramCore_TelegramPeerAccessHash>.self)
    try _v.visit(field: VTOFFSET.title.p, fieldName: "title", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.username.p, fieldName: "username", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.photo.p, fieldName: "photo", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramMediaImageRepresentation>, TelegramCore_TelegramMediaImageRepresentation>>.self)
    try _v.visit(field: VTOFFSET.creationDate.p, fieldName: "creationDate", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.version.p, fieldName: "version", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.participationStatus.p, fieldName: "participationStatus", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.info.p, fieldName: "info", required: true, type: ForwardOffset<TelegramCore_TelegramChannelInfo>.self)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.restrictionInfo.p, fieldName: "restrictionInfo", required: false, type: ForwardOffset<TelegramCore_PeerAccessRestrictionInfo>.self)
    try _v.visit(field: VTOFFSET.adminRights.p, fieldName: "adminRights", required: false, type: ForwardOffset<TelegramCore_TelegramChatAdminRights>.self)
    try _v.visit(field: VTOFFSET.bannedRights.p, fieldName: "bannedRights", required: false, type: ForwardOffset<TelegramCore_TelegramChatBannedRights>.self)
    try _v.visit(field: VTOFFSET.defaultBannedRights.p, fieldName: "defaultBannedRights", required: false, type: ForwardOffset<TelegramCore_TelegramChatBannedRights>.self)
    try _v.visit(field: VTOFFSET.usernames.p, fieldName: "usernames", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramPeerUsername>, TelegramCore_TelegramPeerUsername>>.self)
    try _v.visit(field: VTOFFSET.storiesHidden.p, fieldName: "storiesHidden", required: false, type: TelegramCore_OptionalBool.self)
    try _v.visit(field: VTOFFSET.nameColor.p, fieldName: "nameColor", required: false, type: ForwardOffset<TelegramCore_PeerNameColor>.self)
    try _v.visit(field: VTOFFSET.backgroundEmojiId.p, fieldName: "backgroundEmojiId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.profileColor.p, fieldName: "profileColor", required: false, type: ForwardOffset<TelegramCore_PeerNameColor>.self)
    try _v.visit(field: VTOFFSET.profileBackgroundEmojiId.p, fieldName: "profileBackgroundEmojiId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.emojiStatus.p, fieldName: "emojiStatus", required: false, type: ForwardOffset<TelegramCore_PeerEmojiStatus>.self)
    try _v.visit(field: VTOFFSET.approximateBoostLevel.p, fieldName: "approximateBoostLevel", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.subscriptionUntilDate.p, fieldName: "subscriptionUntilDate", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.verificationIconFileId.p, fieldName: "verificationIconFileId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.sendPaidMessageStars.p, fieldName: "sendPaidMessageStars", required: false, type: ForwardOffset<TelegramCore_StarsAmount>.self)
    try _v.visit(field: VTOFFSET.linkedMonoforumId.p, fieldName: "linkedMonoforumId", required: false, type: TelegramCore_PeerId.self)
    _v.finish()
  }
}

