// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_TelegramPeerAccessHash_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case telegrampeeraccesshashPersonal = 1
  case telegrampeeraccesshashGenericpublic = 2

  public static var max: TelegramCore_TelegramPeerAccessHash_Value { return .telegrampeeraccesshashGenericpublic }
  public static var min: TelegramCore_TelegramPeerAccessHash_Value { return .none_ }
}


public struct TelegramCore_TelegramPeerAccessHash_Personal: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case accessHash = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startTelegramPeerAccessHash_Personal(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func endTelegramPeerAccessHash_Personal(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramPeerAccessHash_Personal(
    _ fbb: inout FlatBufferBuilder,
    accessHash: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramPeerAccessHash_Personal.startTelegramPeerAccessHash_Personal(&fbb)
    TelegramCore_TelegramPeerAccessHash_Personal.add(accessHash: accessHash, &fbb)
    return TelegramCore_TelegramPeerAccessHash_Personal.endTelegramPeerAccessHash_Personal(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramPeerAccessHash_GenericPublic: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case accessHash = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startTelegramPeerAccessHash_GenericPublic(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func endTelegramPeerAccessHash_GenericPublic(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramPeerAccessHash_GenericPublic(
    _ fbb: inout FlatBufferBuilder,
    accessHash: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramPeerAccessHash_GenericPublic.startTelegramPeerAccessHash_GenericPublic(&fbb)
    TelegramCore_TelegramPeerAccessHash_GenericPublic.add(accessHash: accessHash, &fbb)
    return TelegramCore_TelegramPeerAccessHash_GenericPublic.endTelegramPeerAccessHash_GenericPublic(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramPeerAccessHash: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_TelegramPeerAccessHash_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_TelegramPeerAccessHash_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startTelegramPeerAccessHash(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_TelegramPeerAccessHash_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endTelegramPeerAccessHash(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createTelegramPeerAccessHash(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_TelegramPeerAccessHash_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_TelegramPeerAccessHash.startTelegramPeerAccessHash(&fbb)
    TelegramCore_TelegramPeerAccessHash.add(valueType: valueType, &fbb)
    TelegramCore_TelegramPeerAccessHash.add(value: value, &fbb)
    return TelegramCore_TelegramPeerAccessHash.endTelegramPeerAccessHash(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_TelegramPeerAccessHash_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .telegrampeeraccesshashPersonal:
        try ForwardOffset<TelegramCore_TelegramPeerAccessHash_Personal>.verify(&verifier, at: pos, of: TelegramCore_TelegramPeerAccessHash_Personal.self)
      case .telegrampeeraccesshashGenericpublic:
        try ForwardOffset<TelegramCore_TelegramPeerAccessHash_GenericPublic>.verify(&verifier, at: pos, of: TelegramCore_TelegramPeerAccessHash_GenericPublic.self)
      }
    })
    _v.finish()
  }
}

