// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_TelegramPeerUsername: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case flags = 4
    case username = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var username: String! { let o = _accessor.offset(VTOFFSET.username.v); return _accessor.string(at: o) }
  public var usernameSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.username.v) }
  public static func startTelegramPeerUsername(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func add(username: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: username, at: VTOFFSET.username.p) }
  public static func endTelegramPeerUsername(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createTelegramPeerUsername(
    _ fbb: inout FlatBufferBuilder,
    flags: Int32 = 0,
    usernameOffset username: Offset
  ) -> Offset {
    let __start = TelegramCore_TelegramPeerUsername.startTelegramPeerUsername(&fbb)
    TelegramCore_TelegramPeerUsername.add(flags: flags, &fbb)
    TelegramCore_TelegramPeerUsername.add(username: username, &fbb)
    return TelegramCore_TelegramPeerUsername.endTelegramPeerUsername(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.username.p, fieldName: "username", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}
