// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_EmojiMarkup_Content: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case emojimarkupContentEmoji = 1
  case emojimarkupContentSticker = 2

  public static var max: TelegramCore_EmojiMarkup_Content { return .emojimarkupContentSticker }
  public static var min: TelegramCore_EmojiMarkup_Content { return .none_ }
}


public struct TelegramCore_TelegramMediaImageReference: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case imageId = 4
    case accessHash = 6
    case fileReference = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var imageId: Int64 { let o = _accessor.offset(VTOFFSET.imageId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var hasFileReference: Bool { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? false : true }
  public var fileReferenceCount: Int32 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func fileReference(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var fileReference: [UInt8] { return _accessor.getVector(at: VTOFFSET.fileReference.v) ?? [] }
  public static func startTelegramMediaImageReference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(imageId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: imageId, def: 0, at: VTOFFSET.imageId.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func addVectorOf(fileReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: fileReference, at: VTOFFSET.fileReference.p) }
  public static func endTelegramMediaImageReference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaImageReference(
    _ fbb: inout FlatBufferBuilder,
    imageId: Int64 = 0,
    accessHash: Int64 = 0,
    fileReferenceVectorOffset fileReference: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaImageReference.startTelegramMediaImageReference(&fbb)
    TelegramCore_TelegramMediaImageReference.add(imageId: imageId, &fbb)
    TelegramCore_TelegramMediaImageReference.add(accessHash: accessHash, &fbb)
    TelegramCore_TelegramMediaImageReference.addVectorOf(fileReference: fileReference, &fbb)
    return TelegramCore_TelegramMediaImageReference.endTelegramMediaImageReference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.imageId.p, fieldName: "imageId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.fileReference.p, fieldName: "fileReference", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    _v.finish()
  }
}

public struct TelegramCore_VideoRepresentation: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case width = 4
    case height = 6
    case resource = 8
    case startTimestamp = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var width: Int32 { let o = _accessor.offset(VTOFFSET.width.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var height: Int32 { let o = _accessor.offset(VTOFFSET.height.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var resource: TelegramCore_TelegramMediaResource! { let o = _accessor.offset(VTOFFSET.resource.v); return TelegramCore_TelegramMediaResource(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var startTimestamp: Float32 { let o = _accessor.offset(VTOFFSET.startTimestamp.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public static func startVideoRepresentation(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(width: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: width, def: 0, at: VTOFFSET.width.p) }
  public static func add(height: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: height, def: 0, at: VTOFFSET.height.p) }
  public static func add(resource: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resource, at: VTOFFSET.resource.p) }
  public static func add(startTimestamp: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: startTimestamp, def: 0.0, at: VTOFFSET.startTimestamp.p) }
  public static func endVideoRepresentation(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [8]); return end }
  public static func createVideoRepresentation(
    _ fbb: inout FlatBufferBuilder,
    width: Int32 = 0,
    height: Int32 = 0,
    resourceOffset resource: Offset,
    startTimestamp: Float32 = 0.0
  ) -> Offset {
    let __start = TelegramCore_VideoRepresentation.startVideoRepresentation(&fbb)
    TelegramCore_VideoRepresentation.add(width: width, &fbb)
    TelegramCore_VideoRepresentation.add(height: height, &fbb)
    TelegramCore_VideoRepresentation.add(resource: resource, &fbb)
    TelegramCore_VideoRepresentation.add(startTimestamp: startTimestamp, &fbb)
    return TelegramCore_VideoRepresentation.endVideoRepresentation(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.width.p, fieldName: "width", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.height.p, fieldName: "height", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.resource.p, fieldName: "resource", required: true, type: ForwardOffset<TelegramCore_TelegramMediaResource>.self)
    try _v.visit(field: VTOFFSET.startTimestamp.p, fieldName: "startTimestamp", required: false, type: Float32.self)
    _v.finish()
  }
}

public struct TelegramCore_EmojiMarkup_Content_Emoji: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case fileId = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var fileId: Int64 { let o = _accessor.offset(VTOFFSET.fileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startEmojiMarkup_Content_Emoji(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(fileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fileId, def: 0, at: VTOFFSET.fileId.p) }
  public static func endEmojiMarkup_Content_Emoji(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createEmojiMarkup_Content_Emoji(
    _ fbb: inout FlatBufferBuilder,
    fileId: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_EmojiMarkup_Content_Emoji.startEmojiMarkup_Content_Emoji(&fbb)
    TelegramCore_EmojiMarkup_Content_Emoji.add(fileId: fileId, &fbb)
    return TelegramCore_EmojiMarkup_Content_Emoji.endEmojiMarkup_Content_Emoji(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.fileId.p, fieldName: "fileId", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_EmojiMarkup_Content_Sticker: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case packReference = 4
    case fileId = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var packReference: TelegramCore_StickerPackReference! { let o = _accessor.offset(VTOFFSET.packReference.v); return TelegramCore_StickerPackReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var fileId: Int64 { let o = _accessor.offset(VTOFFSET.fileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startEmojiMarkup_Content_Sticker(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(packReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: packReference, at: VTOFFSET.packReference.p) }
  public static func add(fileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fileId, def: 0, at: VTOFFSET.fileId.p) }
  public static func endEmojiMarkup_Content_Sticker(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createEmojiMarkup_Content_Sticker(
    _ fbb: inout FlatBufferBuilder,
    packReferenceOffset packReference: Offset,
    fileId: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_EmojiMarkup_Content_Sticker.startEmojiMarkup_Content_Sticker(&fbb)
    TelegramCore_EmojiMarkup_Content_Sticker.add(packReference: packReference, &fbb)
    TelegramCore_EmojiMarkup_Content_Sticker.add(fileId: fileId, &fbb)
    return TelegramCore_EmojiMarkup_Content_Sticker.endEmojiMarkup_Content_Sticker(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.packReference.p, fieldName: "packReference", required: true, type: ForwardOffset<TelegramCore_StickerPackReference>.self)
    try _v.visit(field: VTOFFSET.fileId.p, fieldName: "fileId", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_EmojiMarkup: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case contentType = 4
    case content = 6
    case backgroundColors = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var contentType: TelegramCore_EmojiMarkup_Content { let o = _accessor.offset(VTOFFSET.contentType.v); return o == 0 ? .none_ : TelegramCore_EmojiMarkup_Content(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func content<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.content.v); return _accessor.union(o) }
  public var hasBackgroundColors: Bool { let o = _accessor.offset(VTOFFSET.backgroundColors.v); return o == 0 ? false : true }
  public var backgroundColorsCount: Int32 { let o = _accessor.offset(VTOFFSET.backgroundColors.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func backgroundColors(at index: Int32) -> Int32 { let o = _accessor.offset(VTOFFSET.backgroundColors.v); return o == 0 ? 0 : _accessor.directRead(of: Int32.self, offset: _accessor.vector(at: o) + index * 4) }
  public var backgroundColors: [Int32] { return _accessor.getVector(at: VTOFFSET.backgroundColors.v) ?? [] }
  public static func startEmojiMarkup(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(contentType: TelegramCore_EmojiMarkup_Content, _ fbb: inout FlatBufferBuilder) { fbb.add(element: contentType.rawValue, def: 0, at: VTOFFSET.contentType.p) }
  public static func add(content: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: content, at: VTOFFSET.content.p) }
  public static func addVectorOf(backgroundColors: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: backgroundColors, at: VTOFFSET.backgroundColors.p) }
  public static func endEmojiMarkup(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createEmojiMarkup(
    _ fbb: inout FlatBufferBuilder,
    contentType: TelegramCore_EmojiMarkup_Content = .none_,
    contentOffset content: Offset,
    backgroundColorsVectorOffset backgroundColors: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_EmojiMarkup.startEmojiMarkup(&fbb)
    TelegramCore_EmojiMarkup.add(contentType: contentType, &fbb)
    TelegramCore_EmojiMarkup.add(content: content, &fbb)
    TelegramCore_EmojiMarkup.addVectorOf(backgroundColors: backgroundColors, &fbb)
    return TelegramCore_EmojiMarkup.endEmojiMarkup(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.contentType.p, unionField: VTOFFSET.content.p, unionKeyName: "contentType", fieldName: "content", required: true, completion: { (verifier, key: TelegramCore_EmojiMarkup_Content, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .emojimarkupContentEmoji:
        try ForwardOffset<TelegramCore_EmojiMarkup_Content_Emoji>.verify(&verifier, at: pos, of: TelegramCore_EmojiMarkup_Content_Emoji.self)
      case .emojimarkupContentSticker:
        try ForwardOffset<TelegramCore_EmojiMarkup_Content_Sticker>.verify(&verifier, at: pos, of: TelegramCore_EmojiMarkup_Content_Sticker.self)
      }
    })
    try _v.visit(field: VTOFFSET.backgroundColors.p, fieldName: "backgroundColors", required: false, type: ForwardOffset<Vector<Int32, Int32>>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaImage: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case imageId = 4
    case representations = 6
    case videoRepresentations = 8
    case immediateThumbnailData = 10
    case emojiMarkup = 12
    case reference = 14
    case partialReference = 16
    case flags = 18
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var imageId: TelegramCore_MediaId! { let o = _accessor.offset(VTOFFSET.imageId.v); return _accessor.readBuffer(of: TelegramCore_MediaId.self, at: o) }
  public var mutableImageId: TelegramCore_MediaId_Mutable! { let o = _accessor.offset(VTOFFSET.imageId.v); return TelegramCore_MediaId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var hasRepresentations: Bool { let o = _accessor.offset(VTOFFSET.representations.v); return o == 0 ? false : true }
  public var representationsCount: Int32 { let o = _accessor.offset(VTOFFSET.representations.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func representations(at index: Int32) -> TelegramCore_TelegramMediaImageRepresentation? { let o = _accessor.offset(VTOFFSET.representations.v); return o == 0 ? nil : TelegramCore_TelegramMediaImageRepresentation(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasVideoRepresentations: Bool { let o = _accessor.offset(VTOFFSET.videoRepresentations.v); return o == 0 ? false : true }
  public var videoRepresentationsCount: Int32 { let o = _accessor.offset(VTOFFSET.videoRepresentations.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func videoRepresentations(at index: Int32) -> TelegramCore_VideoRepresentation? { let o = _accessor.offset(VTOFFSET.videoRepresentations.v); return o == 0 ? nil : TelegramCore_VideoRepresentation(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasImmediateThumbnailData: Bool { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? false : true }
  public var immediateThumbnailDataCount: Int32 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func immediateThumbnailData(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var immediateThumbnailData: [UInt8] { return _accessor.getVector(at: VTOFFSET.immediateThumbnailData.v) ?? [] }
  public var emojiMarkup: TelegramCore_EmojiMarkup? { let o = _accessor.offset(VTOFFSET.emojiMarkup.v); return o == 0 ? nil : TelegramCore_EmojiMarkup(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var reference: TelegramCore_TelegramMediaImageReference? { let o = _accessor.offset(VTOFFSET.reference.v); return o == 0 ? nil : TelegramCore_TelegramMediaImageReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var partialReference: TelegramCore_PartialMediaReference? { let o = _accessor.offset(VTOFFSET.partialReference.v); return o == 0 ? nil : TelegramCore_PartialMediaReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramMediaImage(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 8) }
  public static func add(imageId: TelegramCore_MediaId?, _ fbb: inout FlatBufferBuilder) { guard let imageId = imageId else { return }; fbb.create(struct: imageId, position: VTOFFSET.imageId.p) }
  public static func addVectorOf(representations: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: representations, at: VTOFFSET.representations.p) }
  public static func addVectorOf(videoRepresentations: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: videoRepresentations, at: VTOFFSET.videoRepresentations.p) }
  public static func addVectorOf(immediateThumbnailData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: immediateThumbnailData, at: VTOFFSET.immediateThumbnailData.p) }
  public static func add(emojiMarkup: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: emojiMarkup, at: VTOFFSET.emojiMarkup.p) }
  public static func add(reference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: reference, at: VTOFFSET.reference.p) }
  public static func add(partialReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: partialReference, at: VTOFFSET.partialReference.p) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func endTelegramMediaImage(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createTelegramMediaImage(
    _ fbb: inout FlatBufferBuilder,
    imageId: TelegramCore_MediaId,
    representationsVectorOffset representations: Offset = Offset(),
    videoRepresentationsVectorOffset videoRepresentations: Offset = Offset(),
    immediateThumbnailDataVectorOffset immediateThumbnailData: Offset = Offset(),
    emojiMarkupOffset emojiMarkup: Offset = Offset(),
    referenceOffset reference: Offset = Offset(),
    partialReferenceOffset partialReference: Offset = Offset(),
    flags: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaImage.startTelegramMediaImage(&fbb)
    TelegramCore_TelegramMediaImage.add(imageId: imageId, &fbb)
    TelegramCore_TelegramMediaImage.addVectorOf(representations: representations, &fbb)
    TelegramCore_TelegramMediaImage.addVectorOf(videoRepresentations: videoRepresentations, &fbb)
    TelegramCore_TelegramMediaImage.addVectorOf(immediateThumbnailData: immediateThumbnailData, &fbb)
    TelegramCore_TelegramMediaImage.add(emojiMarkup: emojiMarkup, &fbb)
    TelegramCore_TelegramMediaImage.add(reference: reference, &fbb)
    TelegramCore_TelegramMediaImage.add(partialReference: partialReference, &fbb)
    TelegramCore_TelegramMediaImage.add(flags: flags, &fbb)
    return TelegramCore_TelegramMediaImage.endTelegramMediaImage(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.imageId.p, fieldName: "imageId", required: true, type: TelegramCore_MediaId.self)
    try _v.visit(field: VTOFFSET.representations.p, fieldName: "representations", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramMediaImageRepresentation>, TelegramCore_TelegramMediaImageRepresentation>>.self)
    try _v.visit(field: VTOFFSET.videoRepresentations.p, fieldName: "videoRepresentations", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_VideoRepresentation>, TelegramCore_VideoRepresentation>>.self)
    try _v.visit(field: VTOFFSET.immediateThumbnailData.p, fieldName: "immediateThumbnailData", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.emojiMarkup.p, fieldName: "emojiMarkup", required: false, type: ForwardOffset<TelegramCore_EmojiMarkup>.self)
    try _v.visit(field: VTOFFSET.reference.p, fieldName: "reference", required: false, type: ForwardOffset<TelegramCore_TelegramMediaImageReference>.self)
    try _v.visit(field: VTOFFSET.partialReference.p, fieldName: "partialReference", required: false, type: ForwardOffset<TelegramCore_PartialMediaReference>.self)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    _v.finish()
  }
}
