// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_CloudPeerPhotoSizeSpec: Int32, Enum, Verifiable {
  public typealias T = Int32
  public static var byteSize: Int { return MemoryLayout<Int32>.size }
  public var value: Int32 { return self.rawValue }
  case small = 0
  case fullSize = 1

  public static var max: TelegramCore_CloudPeerPhotoSizeSpec { return .fullSize }
  public static var min: TelegramCore_CloudPeerPhotoSizeSpec { return .small }
}


public enum TelegramCore_TelegramMediaResource_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case telegrammediaresourceCloudfilemediaresource = 1
  case telegrammediaresourceClouddocumentsizemediaresource = 2
  case telegrammediaresourceCloudphotosizemediaresource = 3
  case telegrammediaresourceCloudpeerphotosizemediaresource = 4
  case telegrammediaresourceCloudstickerpackthumbnailmediaresource = 5
  case telegrammediaresourceClouddocumentmediaresource = 6
  case telegrammediaresourceLocalfilemediaresource = 7

  public static var max: TelegramCore_TelegramMediaResource_Value { return .telegrammediaresourceLocalfilemediaresource }
  public static var min: TelegramCore_TelegramMediaResource_Value { return .none_ }
}


public struct TelegramCore_TelegramMediaResource_CloudFileMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case datacenterId = 4
    case volumeId = 6
    case localId = 8
    case secret = 10
    case size = 12
    case fileReference = 14
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var datacenterId: Int32 { let o = _accessor.offset(VTOFFSET.datacenterId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var volumeId: Int64 { let o = _accessor.offset(VTOFFSET.volumeId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var localId: Int32 { let o = _accessor.offset(VTOFFSET.localId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var secret: Int64 { let o = _accessor.offset(VTOFFSET.secret.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var size: Int64 { let o = _accessor.offset(VTOFFSET.size.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var hasFileReference: Bool { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? false : true }
  public var fileReferenceCount: Int32 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func fileReference(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var fileReference: [UInt8] { return _accessor.getVector(at: VTOFFSET.fileReference.v) ?? [] }
  public static func startTelegramMediaResource_CloudFileMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 6) }
  public static func add(datacenterId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: datacenterId, def: 0, at: VTOFFSET.datacenterId.p) }
  public static func add(volumeId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: volumeId, def: 0, at: VTOFFSET.volumeId.p) }
  public static func add(localId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: localId, def: 0, at: VTOFFSET.localId.p) }
  public static func add(secret: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: secret, def: 0, at: VTOFFSET.secret.p) }
  public static func add(size: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: size, def: 0, at: VTOFFSET.size.p) }
  public static func addVectorOf(fileReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: fileReference, at: VTOFFSET.fileReference.p) }
  public static func endTelegramMediaResource_CloudFileMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaResource_CloudFileMediaResource(
    _ fbb: inout FlatBufferBuilder,
    datacenterId: Int32 = 0,
    volumeId: Int64 = 0,
    localId: Int32 = 0,
    secret: Int64 = 0,
    size: Int64 = 0,
    fileReferenceVectorOffset fileReference: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource_CloudFileMediaResource.startTelegramMediaResource_CloudFileMediaResource(&fbb)
    TelegramCore_TelegramMediaResource_CloudFileMediaResource.add(datacenterId: datacenterId, &fbb)
    TelegramCore_TelegramMediaResource_CloudFileMediaResource.add(volumeId: volumeId, &fbb)
    TelegramCore_TelegramMediaResource_CloudFileMediaResource.add(localId: localId, &fbb)
    TelegramCore_TelegramMediaResource_CloudFileMediaResource.add(secret: secret, &fbb)
    TelegramCore_TelegramMediaResource_CloudFileMediaResource.add(size: size, &fbb)
    TelegramCore_TelegramMediaResource_CloudFileMediaResource.addVectorOf(fileReference: fileReference, &fbb)
    return TelegramCore_TelegramMediaResource_CloudFileMediaResource.endTelegramMediaResource_CloudFileMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.datacenterId.p, fieldName: "datacenterId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.volumeId.p, fieldName: "volumeId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.localId.p, fieldName: "localId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.secret.p, fieldName: "secret", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.size.p, fieldName: "size", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.fileReference.p, fieldName: "fileReference", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case datacenterId = 4
    case documentId = 6
    case accessHash = 8
    case sizeSpec = 10
    case fileReference = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var datacenterId: Int32 { let o = _accessor.offset(VTOFFSET.datacenterId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var documentId: Int64 { let o = _accessor.offset(VTOFFSET.documentId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var sizeSpec: String! { let o = _accessor.offset(VTOFFSET.sizeSpec.v); return _accessor.string(at: o) }
  public var sizeSpecSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.sizeSpec.v) }
  public var hasFileReference: Bool { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? false : true }
  public var fileReferenceCount: Int32 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func fileReference(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var fileReference: [UInt8] { return _accessor.getVector(at: VTOFFSET.fileReference.v) ?? [] }
  public static func startTelegramMediaResource_CloudDocumentSizeMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(datacenterId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: datacenterId, def: 0, at: VTOFFSET.datacenterId.p) }
  public static func add(documentId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: documentId, def: 0, at: VTOFFSET.documentId.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func add(sizeSpec: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sizeSpec, at: VTOFFSET.sizeSpec.p) }
  public static func addVectorOf(fileReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: fileReference, at: VTOFFSET.fileReference.p) }
  public static func endTelegramMediaResource_CloudDocumentSizeMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [10]); return end }
  public static func createTelegramMediaResource_CloudDocumentSizeMediaResource(
    _ fbb: inout FlatBufferBuilder,
    datacenterId: Int32 = 0,
    documentId: Int64 = 0,
    accessHash: Int64 = 0,
    sizeSpecOffset sizeSpec: Offset,
    fileReferenceVectorOffset fileReference: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.startTelegramMediaResource_CloudDocumentSizeMediaResource(&fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.add(datacenterId: datacenterId, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.add(documentId: documentId, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.add(accessHash: accessHash, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.add(sizeSpec: sizeSpec, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.addVectorOf(fileReference: fileReference, &fbb)
    return TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.endTelegramMediaResource_CloudDocumentSizeMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.datacenterId.p, fieldName: "datacenterId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.documentId.p, fieldName: "documentId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.sizeSpec.p, fieldName: "sizeSpec", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.fileReference.p, fieldName: "fileReference", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case datacenterId = 4
    case photoId = 6
    case accessHash = 8
    case sizeSpec = 10
    case size = 12
    case fileReference = 14
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var datacenterId: Int32 { let o = _accessor.offset(VTOFFSET.datacenterId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var photoId: Int64 { let o = _accessor.offset(VTOFFSET.photoId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var sizeSpec: String! { let o = _accessor.offset(VTOFFSET.sizeSpec.v); return _accessor.string(at: o) }
  public var sizeSpecSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.sizeSpec.v) }
  public var size: Int64 { let o = _accessor.offset(VTOFFSET.size.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var hasFileReference: Bool { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? false : true }
  public var fileReferenceCount: Int32 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func fileReference(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var fileReference: [UInt8] { return _accessor.getVector(at: VTOFFSET.fileReference.v) ?? [] }
  public static func startTelegramMediaResource_CloudPhotoSizeMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 6) }
  public static func add(datacenterId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: datacenterId, def: 0, at: VTOFFSET.datacenterId.p) }
  public static func add(photoId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: photoId, def: 0, at: VTOFFSET.photoId.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func add(sizeSpec: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sizeSpec, at: VTOFFSET.sizeSpec.p) }
  public static func add(size: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: size, def: 0, at: VTOFFSET.size.p) }
  public static func addVectorOf(fileReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: fileReference, at: VTOFFSET.fileReference.p) }
  public static func endTelegramMediaResource_CloudPhotoSizeMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [10]); return end }
  public static func createTelegramMediaResource_CloudPhotoSizeMediaResource(
    _ fbb: inout FlatBufferBuilder,
    datacenterId: Int32 = 0,
    photoId: Int64 = 0,
    accessHash: Int64 = 0,
    sizeSpecOffset sizeSpec: Offset,
    size: Int64 = 0,
    fileReferenceVectorOffset fileReference: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.startTelegramMediaResource_CloudPhotoSizeMediaResource(&fbb)
    TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.add(datacenterId: datacenterId, &fbb)
    TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.add(photoId: photoId, &fbb)
    TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.add(accessHash: accessHash, &fbb)
    TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.add(sizeSpec: sizeSpec, &fbb)
    TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.add(size: size, &fbb)
    TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.addVectorOf(fileReference: fileReference, &fbb)
    return TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.endTelegramMediaResource_CloudPhotoSizeMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.datacenterId.p, fieldName: "datacenterId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.photoId.p, fieldName: "photoId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.sizeSpec.p, fieldName: "sizeSpec", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.size.p, fieldName: "size", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.fileReference.p, fieldName: "fileReference", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case datacenterId = 4
    case photoId = 6
    case sizeSpec = 8
    case volumeId = 10
    case localId = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var datacenterId: Int32 { let o = _accessor.offset(VTOFFSET.datacenterId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var photoId: Int64 { let o = _accessor.offset(VTOFFSET.photoId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var sizeSpec: TelegramCore_CloudPeerPhotoSizeSpec { let o = _accessor.offset(VTOFFSET.sizeSpec.v); return o == 0 ? .small : TelegramCore_CloudPeerPhotoSizeSpec(rawValue: _accessor.readBuffer(of: Int32.self, at: o)) ?? .small }
  public var volumeId: Int64 { let o = _accessor.offset(VTOFFSET.volumeId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var localId: Int32 { let o = _accessor.offset(VTOFFSET.localId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramMediaResource_CloudPeerPhotoSizeMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(datacenterId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: datacenterId, def: 0, at: VTOFFSET.datacenterId.p) }
  public static func add(photoId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: photoId, def: 0, at: VTOFFSET.photoId.p) }
  public static func add(sizeSpec: TelegramCore_CloudPeerPhotoSizeSpec, _ fbb: inout FlatBufferBuilder) { fbb.add(element: sizeSpec.rawValue, def: 0, at: VTOFFSET.sizeSpec.p) }
  public static func add(volumeId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: volumeId, def: 0, at: VTOFFSET.volumeId.p) }
  public static func add(localId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: localId, def: 0, at: VTOFFSET.localId.p) }
  public static func endTelegramMediaResource_CloudPeerPhotoSizeMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaResource_CloudPeerPhotoSizeMediaResource(
    _ fbb: inout FlatBufferBuilder,
    datacenterId: Int32 = 0,
    photoId: Int64 = 0,
    sizeSpec: TelegramCore_CloudPeerPhotoSizeSpec = .small,
    volumeId: Int64 = 0,
    localId: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.startTelegramMediaResource_CloudPeerPhotoSizeMediaResource(&fbb)
    TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.add(datacenterId: datacenterId, &fbb)
    TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.add(photoId: photoId, &fbb)
    TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.add(sizeSpec: sizeSpec, &fbb)
    TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.add(volumeId: volumeId, &fbb)
    TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.add(localId: localId, &fbb)
    return TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.endTelegramMediaResource_CloudPeerPhotoSizeMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.datacenterId.p, fieldName: "datacenterId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.photoId.p, fieldName: "photoId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.sizeSpec.p, fieldName: "sizeSpec", required: false, type: TelegramCore_CloudPeerPhotoSizeSpec.self)
    try _v.visit(field: VTOFFSET.volumeId.p, fieldName: "volumeId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.localId.p, fieldName: "localId", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case datacenterId = 4
    case thumbVersion = 6
    case volumeId = 8
    case localId = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var datacenterId: Int32 { let o = _accessor.offset(VTOFFSET.datacenterId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var thumbVersion: Int32 { let o = _accessor.offset(VTOFFSET.thumbVersion.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var volumeId: Int64 { let o = _accessor.offset(VTOFFSET.volumeId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var localId: Int32 { let o = _accessor.offset(VTOFFSET.localId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramMediaResource_CloudStickerPackThumbnailMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(datacenterId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: datacenterId, def: 0, at: VTOFFSET.datacenterId.p) }
  public static func add(thumbVersion: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: thumbVersion, def: 0, at: VTOFFSET.thumbVersion.p) }
  public static func add(volumeId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: volumeId, def: 0, at: VTOFFSET.volumeId.p) }
  public static func add(localId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: localId, def: 0, at: VTOFFSET.localId.p) }
  public static func endTelegramMediaResource_CloudStickerPackThumbnailMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaResource_CloudStickerPackThumbnailMediaResource(
    _ fbb: inout FlatBufferBuilder,
    datacenterId: Int32 = 0,
    thumbVersion: Int32 = 0,
    volumeId: Int64 = 0,
    localId: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource.startTelegramMediaResource_CloudStickerPackThumbnailMediaResource(&fbb)
    TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource.add(datacenterId: datacenterId, &fbb)
    TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource.add(thumbVersion: thumbVersion, &fbb)
    TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource.add(volumeId: volumeId, &fbb)
    TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource.add(localId: localId, &fbb)
    return TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource.endTelegramMediaResource_CloudStickerPackThumbnailMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.datacenterId.p, fieldName: "datacenterId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.thumbVersion.p, fieldName: "thumbVersion", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.volumeId.p, fieldName: "volumeId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.localId.p, fieldName: "localId", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaResource_CloudDocumentMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case datacenterId = 4
    case fileId = 6
    case accessHash = 8
    case size = 10
    case fileReference = 12
    case fileName = 14
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var datacenterId: Int32 { let o = _accessor.offset(VTOFFSET.datacenterId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var fileId: Int64 { let o = _accessor.offset(VTOFFSET.fileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var size: Int64 { let o = _accessor.offset(VTOFFSET.size.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var hasFileReference: Bool { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? false : true }
  public var fileReferenceCount: Int32 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func fileReference(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.fileReference.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var fileReference: [UInt8] { return _accessor.getVector(at: VTOFFSET.fileReference.v) ?? [] }
  public var fileName: String? { let o = _accessor.offset(VTOFFSET.fileName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var fileNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.fileName.v) }
  public static func startTelegramMediaResource_CloudDocumentMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 6) }
  public static func add(datacenterId: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: datacenterId, def: 0, at: VTOFFSET.datacenterId.p) }
  public static func add(fileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fileId, def: 0, at: VTOFFSET.fileId.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func add(size: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: size, def: 0, at: VTOFFSET.size.p) }
  public static func addVectorOf(fileReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: fileReference, at: VTOFFSET.fileReference.p) }
  public static func add(fileName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: fileName, at: VTOFFSET.fileName.p) }
  public static func endTelegramMediaResource_CloudDocumentMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaResource_CloudDocumentMediaResource(
    _ fbb: inout FlatBufferBuilder,
    datacenterId: Int32 = 0,
    fileId: Int64 = 0,
    accessHash: Int64 = 0,
    size: Int64 = 0,
    fileReferenceVectorOffset fileReference: Offset = Offset(),
    fileNameOffset fileName: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.startTelegramMediaResource_CloudDocumentMediaResource(&fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.add(datacenterId: datacenterId, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.add(fileId: fileId, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.add(accessHash: accessHash, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.add(size: size, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.addVectorOf(fileReference: fileReference, &fbb)
    TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.add(fileName: fileName, &fbb)
    return TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.endTelegramMediaResource_CloudDocumentMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.datacenterId.p, fieldName: "datacenterId", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.fileId.p, fieldName: "fileId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.size.p, fieldName: "size", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.fileReference.p, fieldName: "fileReference", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.fileName.p, fieldName: "fileName", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaResource_LocalFileMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case fileId = 4
    case size = 6
    case isSecretRelated = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var fileId: Int64 { let o = _accessor.offset(VTOFFSET.fileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var size: Int64 { let o = _accessor.offset(VTOFFSET.size.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var isSecretRelated: Bool { let o = _accessor.offset(VTOFFSET.isSecretRelated.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startTelegramMediaResource_LocalFileMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(fileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: fileId, def: 0, at: VTOFFSET.fileId.p) }
  public static func add(size: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: size, def: 0, at: VTOFFSET.size.p) }
  public static func add(isSecretRelated: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isSecretRelated, def: false,
   at: VTOFFSET.isSecretRelated.p) }
  public static func endTelegramMediaResource_LocalFileMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaResource_LocalFileMediaResource(
    _ fbb: inout FlatBufferBuilder,
    fileId: Int64 = 0,
    size: Int64 = 0,
    isSecretRelated: Bool = false
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource_LocalFileMediaResource.startTelegramMediaResource_LocalFileMediaResource(&fbb)
    TelegramCore_TelegramMediaResource_LocalFileMediaResource.add(fileId: fileId, &fbb)
    TelegramCore_TelegramMediaResource_LocalFileMediaResource.add(size: size, &fbb)
    TelegramCore_TelegramMediaResource_LocalFileMediaResource.add(isSecretRelated: isSecretRelated, &fbb)
    return TelegramCore_TelegramMediaResource_LocalFileMediaResource.endTelegramMediaResource_LocalFileMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.fileId.p, fieldName: "fileId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.size.p, fieldName: "size", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.isSecretRelated.p, fieldName: "isSecretRelated", required: false, type: Bool.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaResource: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_TelegramMediaResource_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_TelegramMediaResource_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startTelegramMediaResource(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_TelegramMediaResource_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endTelegramMediaResource(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createTelegramMediaResource(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_TelegramMediaResource_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaResource.startTelegramMediaResource(&fbb)
    TelegramCore_TelegramMediaResource.add(valueType: valueType, &fbb)
    TelegramCore_TelegramMediaResource.add(value: value, &fbb)
    return TelegramCore_TelegramMediaResource.endTelegramMediaResource(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_TelegramMediaResource_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .telegrammediaresourceCloudfilemediaresource:
        try ForwardOffset<TelegramCore_TelegramMediaResource_CloudFileMediaResource>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaResource_CloudFileMediaResource.self)
      case .telegrammediaresourceClouddocumentsizemediaresource:
        try ForwardOffset<TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaResource_CloudDocumentSizeMediaResource.self)
      case .telegrammediaresourceCloudphotosizemediaresource:
        try ForwardOffset<TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaResource_CloudPhotoSizeMediaResource.self)
      case .telegrammediaresourceCloudpeerphotosizemediaresource:
        try ForwardOffset<TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaResource_CloudPeerPhotoSizeMediaResource.self)
      case .telegrammediaresourceCloudstickerpackthumbnailmediaresource:
        try ForwardOffset<TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaResource_CloudStickerPackThumbnailMediaResource.self)
      case .telegrammediaresourceClouddocumentmediaresource:
        try ForwardOffset<TelegramCore_TelegramMediaResource_CloudDocumentMediaResource>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaResource_CloudDocumentMediaResource.self)
      case .telegrammediaresourceLocalfilemediaresource:
        try ForwardOffset<TelegramCore_TelegramMediaResource_LocalFileMediaResource>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaResource_LocalFileMediaResource.self)
      }
    })
    _v.finish()
  }
}
