// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_TelegramGroupRole_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case telegramgrouproleCreator = 1
  case telegramgrouproleAdmin = 2
  case telegramgrouproleMember = 3

  public static var max: TelegramCore_TelegramGroupRole_Value { return .telegramgrouproleMember }
  public static var min: TelegramCore_TelegramGroupRole_Value { return .none_ }
}


public struct TelegramCore_TelegramGroupRole_Creator: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case rank = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var rank: String? { let o = _accessor.offset(VTOFFSET.rank.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var rankSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.rank.v) }
  public static func startTelegramGroupRole_Creator(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(rank: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: rank, at: VTOFFSET.rank.p) }
  public static func endTelegramGroupRole_Creator(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramGroupRole_Creator(
    _ fbb: inout FlatBufferBuilder,
    rankOffset rank: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramGroupRole_Creator.startTelegramGroupRole_Creator(&fbb)
    TelegramCore_TelegramGroupRole_Creator.add(rank: rank, &fbb)
    return TelegramCore_TelegramGroupRole_Creator.endTelegramGroupRole_Creator(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.rank.p, fieldName: "rank", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramGroupRole_Admin: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case rights = 4
    case rank = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var rights: TelegramCore_TelegramChatAdminRights! { let o = _accessor.offset(VTOFFSET.rights.v); return TelegramCore_TelegramChatAdminRights(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var rank: String? { let o = _accessor.offset(VTOFFSET.rank.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var rankSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.rank.v) }
  public static func startTelegramGroupRole_Admin(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(rights: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: rights, at: VTOFFSET.rights.p) }
  public static func add(rank: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: rank, at: VTOFFSET.rank.p) }
  public static func endTelegramGroupRole_Admin(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createTelegramGroupRole_Admin(
    _ fbb: inout FlatBufferBuilder,
    rightsOffset rights: Offset,
    rankOffset rank: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramGroupRole_Admin.startTelegramGroupRole_Admin(&fbb)
    TelegramCore_TelegramGroupRole_Admin.add(rights: rights, &fbb)
    TelegramCore_TelegramGroupRole_Admin.add(rank: rank, &fbb)
    return TelegramCore_TelegramGroupRole_Admin.endTelegramGroupRole_Admin(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.rights.p, fieldName: "rights", required: true, type: ForwardOffset<TelegramCore_TelegramChatAdminRights>.self)
    try _v.visit(field: VTOFFSET.rank.p, fieldName: "rank", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramGroupRole_Member: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startTelegramGroupRole_Member(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endTelegramGroupRole_Member(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_TelegramGroupRole: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_TelegramGroupRole_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_TelegramGroupRole_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startTelegramGroupRole(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_TelegramGroupRole_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endTelegramGroupRole(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createTelegramGroupRole(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_TelegramGroupRole_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_TelegramGroupRole.startTelegramGroupRole(&fbb)
    TelegramCore_TelegramGroupRole.add(valueType: valueType, &fbb)
    TelegramCore_TelegramGroupRole.add(value: value, &fbb)
    return TelegramCore_TelegramGroupRole.endTelegramGroupRole(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_TelegramGroupRole_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .telegramgrouproleCreator:
        try ForwardOffset<TelegramCore_TelegramGroupRole_Creator>.verify(&verifier, at: pos, of: TelegramCore_TelegramGroupRole_Creator.self)
      case .telegramgrouproleAdmin:
        try ForwardOffset<TelegramCore_TelegramGroupRole_Admin>.verify(&verifier, at: pos, of: TelegramCore_TelegramGroupRole_Admin.self)
      case .telegramgrouproleMember:
        try ForwardOffset<TelegramCore_TelegramGroupRole_Member>.verify(&verifier, at: pos, of: TelegramCore_TelegramGroupRole_Member.self)
      }
    })
    _v.finish()
  }
}

public struct TelegramCore_TelegramGroupToChannelMigrationReference: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case peerId = 4
    case accessHash = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var peerId: Int64 { let o = _accessor.offset(VTOFFSET.peerId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var accessHash: Int64 { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startTelegramGroupToChannelMigrationReference(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(peerId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: peerId, def: 0, at: VTOFFSET.peerId.p) }
  public static func add(accessHash: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: accessHash, def: 0, at: VTOFFSET.accessHash.p) }
  public static func endTelegramGroupToChannelMigrationReference(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramGroupToChannelMigrationReference(
    _ fbb: inout FlatBufferBuilder,
    peerId: Int64 = 0,
    accessHash: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramGroupToChannelMigrationReference.startTelegramGroupToChannelMigrationReference(&fbb)
    TelegramCore_TelegramGroupToChannelMigrationReference.add(peerId: peerId, &fbb)
    TelegramCore_TelegramGroupToChannelMigrationReference.add(accessHash: accessHash, &fbb)
    return TelegramCore_TelegramGroupToChannelMigrationReference.endTelegramGroupToChannelMigrationReference(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.peerId.p, fieldName: "peerId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: Int64.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramGroup: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case title = 6
    case photo = 8
    case participantCount = 10
    case role = 12
    case membership = 14
    case flags = 16
    case defaultBannedRights = 18
    case migrationReference = 20
    case creationDate = 22
    case version = 24
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: TelegramCore_PeerId! { let o = _accessor.offset(VTOFFSET.id.v); return _accessor.readBuffer(of: TelegramCore_PeerId.self, at: o) }
  public var mutableId: TelegramCore_PeerId_Mutable! { let o = _accessor.offset(VTOFFSET.id.v); return TelegramCore_PeerId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var title: String! { let o = _accessor.offset(VTOFFSET.title.v); return _accessor.string(at: o) }
  public var titleSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.title.v) }
  public var hasPhoto: Bool { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? false : true }
  public var photoCount: Int32 { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func photo(at index: Int32) -> TelegramCore_TelegramMediaImageRepresentation? { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? nil : TelegramCore_TelegramMediaImageRepresentation(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var participantCount: Int32 { let o = _accessor.offset(VTOFFSET.participantCount.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var role: TelegramCore_TelegramGroupRole! { let o = _accessor.offset(VTOFFSET.role.v); return TelegramCore_TelegramGroupRole(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var membership: Int32 { let o = _accessor.offset(VTOFFSET.membership.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var defaultBannedRights: TelegramCore_TelegramChatBannedRights? { let o = _accessor.offset(VTOFFSET.defaultBannedRights.v); return o == 0 ? nil : TelegramCore_TelegramChatBannedRights(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var migrationReference: TelegramCore_TelegramGroupToChannelMigrationReference? { let o = _accessor.offset(VTOFFSET.migrationReference.v); return o == 0 ? nil : TelegramCore_TelegramGroupToChannelMigrationReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var creationDate: Int32 { let o = _accessor.offset(VTOFFSET.creationDate.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var version: Int32 { let o = _accessor.offset(VTOFFSET.version.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramGroup(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 11) }
  public static func add(id: TelegramCore_PeerId?, _ fbb: inout FlatBufferBuilder) { guard let id = id else { return }; fbb.create(struct: id, position: VTOFFSET.id.p) }
  public static func add(title: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: title, at: VTOFFSET.title.p) }
  public static func addVectorOf(photo: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: photo, at: VTOFFSET.photo.p) }
  public static func add(participantCount: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: participantCount, def: 0, at: VTOFFSET.participantCount.p) }
  public static func add(role: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: role, at: VTOFFSET.role.p) }
  public static func add(membership: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: membership, def: 0, at: VTOFFSET.membership.p) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func add(defaultBannedRights: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: defaultBannedRights, at: VTOFFSET.defaultBannedRights.p) }
  public static func add(migrationReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: migrationReference, at: VTOFFSET.migrationReference.p) }
  public static func add(creationDate: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: creationDate, def: 0, at: VTOFFSET.creationDate.p) }
  public static func add(version: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: version, def: 0, at: VTOFFSET.version.p) }
  public static func endTelegramGroup(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 6, 8, 12]); return end }
  public static func createTelegramGroup(
    _ fbb: inout FlatBufferBuilder,
    id: TelegramCore_PeerId,
    titleOffset title: Offset,
    photoVectorOffset photo: Offset,
    participantCount: Int32 = 0,
    roleOffset role: Offset,
    membership: Int32 = 0,
    flags: Int32 = 0,
    defaultBannedRightsOffset defaultBannedRights: Offset = Offset(),
    migrationReferenceOffset migrationReference: Offset = Offset(),
    creationDate: Int32 = 0,
    version: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramGroup.startTelegramGroup(&fbb)
    TelegramCore_TelegramGroup.add(id: id, &fbb)
    TelegramCore_TelegramGroup.add(title: title, &fbb)
    TelegramCore_TelegramGroup.addVectorOf(photo: photo, &fbb)
    TelegramCore_TelegramGroup.add(participantCount: participantCount, &fbb)
    TelegramCore_TelegramGroup.add(role: role, &fbb)
    TelegramCore_TelegramGroup.add(membership: membership, &fbb)
    TelegramCore_TelegramGroup.add(flags: flags, &fbb)
    TelegramCore_TelegramGroup.add(defaultBannedRights: defaultBannedRights, &fbb)
    TelegramCore_TelegramGroup.add(migrationReference: migrationReference, &fbb)
    TelegramCore_TelegramGroup.add(creationDate: creationDate, &fbb)
    TelegramCore_TelegramGroup.add(version: version, &fbb)
    return TelegramCore_TelegramGroup.endTelegramGroup(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: true, type: TelegramCore_PeerId.self)
    try _v.visit(field: VTOFFSET.title.p, fieldName: "title", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.photo.p, fieldName: "photo", required: true, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramMediaImageRepresentation>, TelegramCore_TelegramMediaImageRepresentation>>.self)
    try _v.visit(field: VTOFFSET.participantCount.p, fieldName: "participantCount", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.role.p, fieldName: "role", required: true, type: ForwardOffset<TelegramCore_TelegramGroupRole>.self)
    try _v.visit(field: VTOFFSET.membership.p, fieldName: "membership", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.defaultBannedRights.p, fieldName: "defaultBannedRights", required: false, type: ForwardOffset<TelegramCore_TelegramChatBannedRights>.self)
    try _v.visit(field: VTOFFSET.migrationReference.p, fieldName: "migrationReference", required: false, type: ForwardOffset<TelegramCore_TelegramGroupToChannelMigrationReference>.self)
    try _v.visit(field: VTOFFSET.creationDate.p, fieldName: "creationDate", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.version.p, fieldName: "version", required: false, type: Int32.self)
    _v.finish()
  }
}

