// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_TelegramMediaFileAttribute_Value: UInt8, UnionEnum {
  public typealias T = UInt8

  public init?(value: T) {
    self.init(rawValue: value)
  }

  public static var byteSize: Int { return MemoryLayout<UInt8>.size }
  public var value: UInt8 { return self.rawValue }
  case none_ = 0
  case telegrammediafileattributeFilename = 1
  case telegrammediafileattributeSticker = 2
  case telegrammediafileattributeImagesize = 3
  case telegrammediafileattributeAnimated = 4
  case telegrammediafileattributeVideo = 5
  case telegrammediafileattributeAudio = 6
  case telegrammediafileattributeHaslinkedstickers = 7
  case telegrammediafileattributeHintfileislarge = 8
  case telegrammediafileattributeHintisvalidated = 9
  case telegrammediafileattributeNopremium = 10
  case telegrammediafileattributeCustomemoji = 11

  public static var max: TelegramCore_TelegramMediaFileAttribute_Value { return .telegrammediafileattributeCustomemoji }
  public static var min: TelegramCore_TelegramMediaFileAttribute_Value { return .none_ }
}


public struct TelegramCore_TelegramMediaFileAttribute_FileName: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case fileName = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var fileName: String! { let o = _accessor.offset(VTOFFSET.fileName.v); return _accessor.string(at: o) }
  public var fileNameSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.fileName.v) }
  public static func startTelegramMediaFileAttribute_FileName(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(fileName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: fileName, at: VTOFFSET.fileName.p) }
  public static func endTelegramMediaFileAttribute_FileName(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createTelegramMediaFileAttribute_FileName(
    _ fbb: inout FlatBufferBuilder,
    fileNameOffset fileName: Offset
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFileAttribute_FileName.startTelegramMediaFileAttribute_FileName(&fbb)
    TelegramCore_TelegramMediaFileAttribute_FileName.add(fileName: fileName, &fbb)
    return TelegramCore_TelegramMediaFileAttribute_FileName.endTelegramMediaFileAttribute_FileName(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.fileName.p, fieldName: "fileName", required: true, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_StickerMaskCoords: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case n = 4
    case x = 6
    case y = 8
    case zoom = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var n: Int32 { let o = _accessor.offset(VTOFFSET.n.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var x: Float32 { let o = _accessor.offset(VTOFFSET.x.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public var y: Float32 { let o = _accessor.offset(VTOFFSET.y.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public var zoom: Float32 { let o = _accessor.offset(VTOFFSET.zoom.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public static func startStickerMaskCoords(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(n: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: n, def: 0, at: VTOFFSET.n.p) }
  public static func add(x: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: x, def: 0.0, at: VTOFFSET.x.p) }
  public static func add(y: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: y, def: 0.0, at: VTOFFSET.y.p) }
  public static func add(zoom: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: zoom, def: 0.0, at: VTOFFSET.zoom.p) }
  public static func endStickerMaskCoords(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createStickerMaskCoords(
    _ fbb: inout FlatBufferBuilder,
    n: Int32 = 0,
    x: Float32 = 0.0,
    y: Float32 = 0.0,
    zoom: Float32 = 0.0
  ) -> Offset {
    let __start = TelegramCore_StickerMaskCoords.startStickerMaskCoords(&fbb)
    TelegramCore_StickerMaskCoords.add(n: n, &fbb)
    TelegramCore_StickerMaskCoords.add(x: x, &fbb)
    TelegramCore_StickerMaskCoords.add(y: y, &fbb)
    TelegramCore_StickerMaskCoords.add(zoom: zoom, &fbb)
    return TelegramCore_StickerMaskCoords.endStickerMaskCoords(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.n.p, fieldName: "n", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.x.p, fieldName: "x", required: false, type: Float32.self)
    try _v.visit(field: VTOFFSET.y.p, fieldName: "y", required: false, type: Float32.self)
    try _v.visit(field: VTOFFSET.zoom.p, fieldName: "zoom", required: false, type: Float32.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_Sticker: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case displayText = 4
    case packReference = 6
    case maskData = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var displayText: String! { let o = _accessor.offset(VTOFFSET.displayText.v); return _accessor.string(at: o) }
  public var displayTextSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.displayText.v) }
  public var packReference: TelegramCore_StickerPackReference? { let o = _accessor.offset(VTOFFSET.packReference.v); return o == 0 ? nil : TelegramCore_StickerPackReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var maskData: TelegramCore_StickerMaskCoords? { let o = _accessor.offset(VTOFFSET.maskData.v); return o == 0 ? nil : TelegramCore_StickerMaskCoords(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startTelegramMediaFileAttribute_Sticker(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(displayText: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: displayText, at: VTOFFSET.displayText.p) }
  public static func add(packReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: packReference, at: VTOFFSET.packReference.p) }
  public static func add(maskData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: maskData, at: VTOFFSET.maskData.p) }
  public static func endTelegramMediaFileAttribute_Sticker(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createTelegramMediaFileAttribute_Sticker(
    _ fbb: inout FlatBufferBuilder,
    displayTextOffset displayText: Offset,
    packReferenceOffset packReference: Offset = Offset(),
    maskDataOffset maskData: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFileAttribute_Sticker.startTelegramMediaFileAttribute_Sticker(&fbb)
    TelegramCore_TelegramMediaFileAttribute_Sticker.add(displayText: displayText, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Sticker.add(packReference: packReference, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Sticker.add(maskData: maskData, &fbb)
    return TelegramCore_TelegramMediaFileAttribute_Sticker.endTelegramMediaFileAttribute_Sticker(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.displayText.p, fieldName: "displayText", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.packReference.p, fieldName: "packReference", required: false, type: ForwardOffset<TelegramCore_StickerPackReference>.self)
    try _v.visit(field: VTOFFSET.maskData.p, fieldName: "maskData", required: false, type: ForwardOffset<TelegramCore_StickerMaskCoords>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_ImageSize: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case width = 4
    case height = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var width: Int32 { let o = _accessor.offset(VTOFFSET.width.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var height: Int32 { let o = _accessor.offset(VTOFFSET.height.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramMediaFileAttribute_ImageSize(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(width: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: width, def: 0, at: VTOFFSET.width.p) }
  public static func add(height: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: height, def: 0, at: VTOFFSET.height.p) }
  public static func endTelegramMediaFileAttribute_ImageSize(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaFileAttribute_ImageSize(
    _ fbb: inout FlatBufferBuilder,
    width: Int32 = 0,
    height: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFileAttribute_ImageSize.startTelegramMediaFileAttribute_ImageSize(&fbb)
    TelegramCore_TelegramMediaFileAttribute_ImageSize.add(width: width, &fbb)
    TelegramCore_TelegramMediaFileAttribute_ImageSize.add(height: height, &fbb)
    return TelegramCore_TelegramMediaFileAttribute_ImageSize.endTelegramMediaFileAttribute_ImageSize(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.width.p, fieldName: "width", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.height.p, fieldName: "height", required: false, type: Int32.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_Animated: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startTelegramMediaFileAttribute_Animated(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endTelegramMediaFileAttribute_Animated(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_Video: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case duration = 4
    case width = 6
    case height = 8
    case flags = 10
    case preloadSize = 12
    case coverTime = 14
    case videoCodec = 16
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var duration: Float32 { let o = _accessor.offset(VTOFFSET.duration.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public var width: Int32 { let o = _accessor.offset(VTOFFSET.width.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var height: Int32 { let o = _accessor.offset(VTOFFSET.height.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var preloadSize: Int32 { let o = _accessor.offset(VTOFFSET.preloadSize.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var coverTime: Float32 { let o = _accessor.offset(VTOFFSET.coverTime.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public var videoCodec: String? { let o = _accessor.offset(VTOFFSET.videoCodec.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var videoCodecSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.videoCodec.v) }
  public static func startTelegramMediaFileAttribute_Video(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 7) }
  public static func add(duration: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: duration, def: 0.0, at: VTOFFSET.duration.p) }
  public static func add(width: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: width, def: 0, at: VTOFFSET.width.p) }
  public static func add(height: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: height, def: 0, at: VTOFFSET.height.p) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func add(preloadSize: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: preloadSize, def: 0, at: VTOFFSET.preloadSize.p) }
  public static func add(coverTime: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: coverTime, def: 0.0, at: VTOFFSET.coverTime.p) }
  public static func add(videoCodec: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: videoCodec, at: VTOFFSET.videoCodec.p) }
  public static func endTelegramMediaFileAttribute_Video(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaFileAttribute_Video(
    _ fbb: inout FlatBufferBuilder,
    duration: Float32 = 0.0,
    width: Int32 = 0,
    height: Int32 = 0,
    flags: Int32 = 0,
    preloadSize: Int32 = 0,
    coverTime: Float32 = 0.0,
    videoCodecOffset videoCodec: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFileAttribute_Video.startTelegramMediaFileAttribute_Video(&fbb)
    TelegramCore_TelegramMediaFileAttribute_Video.add(duration: duration, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Video.add(width: width, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Video.add(height: height, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Video.add(flags: flags, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Video.add(preloadSize: preloadSize, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Video.add(coverTime: coverTime, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Video.add(videoCodec: videoCodec, &fbb)
    return TelegramCore_TelegramMediaFileAttribute_Video.endTelegramMediaFileAttribute_Video(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.duration.p, fieldName: "duration", required: false, type: Float32.self)
    try _v.visit(field: VTOFFSET.width.p, fieldName: "width", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.height.p, fieldName: "height", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.preloadSize.p, fieldName: "preloadSize", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.coverTime.p, fieldName: "coverTime", required: false, type: Float32.self)
    try _v.visit(field: VTOFFSET.videoCodec.p, fieldName: "videoCodec", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_Audio: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case isVoice = 4
    case duration = 6
    case title = 8
    case performer = 10
    case waveform = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var isVoice: Bool { let o = _accessor.offset(VTOFFSET.isVoice.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var duration: Int32 { let o = _accessor.offset(VTOFFSET.duration.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var title: String? { let o = _accessor.offset(VTOFFSET.title.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var titleSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.title.v) }
  public var performer: String? { let o = _accessor.offset(VTOFFSET.performer.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var performerSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.performer.v) }
  public var hasWaveform: Bool { let o = _accessor.offset(VTOFFSET.waveform.v); return o == 0 ? false : true }
  public var waveformCount: Int32 { let o = _accessor.offset(VTOFFSET.waveform.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func waveform(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.waveform.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var waveform: [UInt8] { return _accessor.getVector(at: VTOFFSET.waveform.v) ?? [] }
  public static func startTelegramMediaFileAttribute_Audio(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(isVoice: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isVoice, def: false,
   at: VTOFFSET.isVoice.p) }
  public static func add(duration: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: duration, def: 0, at: VTOFFSET.duration.p) }
  public static func add(title: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: title, at: VTOFFSET.title.p) }
  public static func add(performer: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: performer, at: VTOFFSET.performer.p) }
  public static func addVectorOf(waveform: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: waveform, at: VTOFFSET.waveform.p) }
  public static func endTelegramMediaFileAttribute_Audio(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramMediaFileAttribute_Audio(
    _ fbb: inout FlatBufferBuilder,
    isVoice: Bool = false,
    duration: Int32 = 0,
    titleOffset title: Offset = Offset(),
    performerOffset performer: Offset = Offset(),
    waveformVectorOffset waveform: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFileAttribute_Audio.startTelegramMediaFileAttribute_Audio(&fbb)
    TelegramCore_TelegramMediaFileAttribute_Audio.add(isVoice: isVoice, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Audio.add(duration: duration, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Audio.add(title: title, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Audio.add(performer: performer, &fbb)
    TelegramCore_TelegramMediaFileAttribute_Audio.addVectorOf(waveform: waveform, &fbb)
    return TelegramCore_TelegramMediaFileAttribute_Audio.endTelegramMediaFileAttribute_Audio(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.isVoice.p, fieldName: "isVoice", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.duration.p, fieldName: "duration", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.title.p, fieldName: "title", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.performer.p, fieldName: "performer", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.waveform.p, fieldName: "waveform", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_HasLinkedStickers: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startTelegramMediaFileAttribute_HasLinkedStickers(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endTelegramMediaFileAttribute_HasLinkedStickers(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_HintFileIsLarge: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startTelegramMediaFileAttribute_HintFileIsLarge(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endTelegramMediaFileAttribute_HintFileIsLarge(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_HintIsValidated: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startTelegramMediaFileAttribute_HintIsValidated(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endTelegramMediaFileAttribute_HintIsValidated(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_NoPremium: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  public static func startTelegramMediaFileAttribute_NoPremium(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 0) }
  public static func endTelegramMediaFileAttribute_NoPremium(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute_CustomEmoji: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case isPremium = 4
    case isSingleColor = 6
    case alt = 8
    case packReference = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var isPremium: Bool { let o = _accessor.offset(VTOFFSET.isPremium.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var isSingleColor: Bool { let o = _accessor.offset(VTOFFSET.isSingleColor.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var alt: String! { let o = _accessor.offset(VTOFFSET.alt.v); return _accessor.string(at: o) }
  public var altSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.alt.v) }
  public var packReference: TelegramCore_StickerPackReference? { let o = _accessor.offset(VTOFFSET.packReference.v); return o == 0 ? nil : TelegramCore_StickerPackReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startTelegramMediaFileAttribute_CustomEmoji(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(isPremium: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isPremium, def: false,
   at: VTOFFSET.isPremium.p) }
  public static func add(isSingleColor: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isSingleColor, def: false,
   at: VTOFFSET.isSingleColor.p) }
  public static func add(alt: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: alt, at: VTOFFSET.alt.p) }
  public static func add(packReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: packReference, at: VTOFFSET.packReference.p) }
  public static func endTelegramMediaFileAttribute_CustomEmoji(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [8]); return end }
  public static func createTelegramMediaFileAttribute_CustomEmoji(
    _ fbb: inout FlatBufferBuilder,
    isPremium: Bool = false,
    isSingleColor: Bool = false,
    altOffset alt: Offset,
    packReferenceOffset packReference: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFileAttribute_CustomEmoji.startTelegramMediaFileAttribute_CustomEmoji(&fbb)
    TelegramCore_TelegramMediaFileAttribute_CustomEmoji.add(isPremium: isPremium, &fbb)
    TelegramCore_TelegramMediaFileAttribute_CustomEmoji.add(isSingleColor: isSingleColor, &fbb)
    TelegramCore_TelegramMediaFileAttribute_CustomEmoji.add(alt: alt, &fbb)
    TelegramCore_TelegramMediaFileAttribute_CustomEmoji.add(packReference: packReference, &fbb)
    return TelegramCore_TelegramMediaFileAttribute_CustomEmoji.endTelegramMediaFileAttribute_CustomEmoji(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.isPremium.p, fieldName: "isPremium", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.isSingleColor.p, fieldName: "isSingleColor", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.alt.p, fieldName: "alt", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.packReference.p, fieldName: "packReference", required: false, type: ForwardOffset<TelegramCore_StickerPackReference>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramMediaFileAttribute: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case valueType = 4
    case value = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var valueType: TelegramCore_TelegramMediaFileAttribute_Value { let o = _accessor.offset(VTOFFSET.valueType.v); return o == 0 ? .none_ : TelegramCore_TelegramMediaFileAttribute_Value(rawValue: _accessor.readBuffer(of: UInt8.self, at: o)) ?? .none_ }
  public func value<T: FlatbuffersInitializable>(type: T.Type) -> T! { let o = _accessor.offset(VTOFFSET.value.v); return _accessor.union(o) }
  public static func startTelegramMediaFileAttribute(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(valueType: TelegramCore_TelegramMediaFileAttribute_Value, _ fbb: inout FlatBufferBuilder) { fbb.add(element: valueType.rawValue, def: 0, at: VTOFFSET.valueType.p) }
  public static func add(value: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: value, at: VTOFFSET.value.p) }
  public static func endTelegramMediaFileAttribute(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [6]); return end }
  public static func createTelegramMediaFileAttribute(
    _ fbb: inout FlatBufferBuilder,
    valueType: TelegramCore_TelegramMediaFileAttribute_Value = .none_,
    valueOffset value: Offset
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFileAttribute.startTelegramMediaFileAttribute(&fbb)
    TelegramCore_TelegramMediaFileAttribute.add(valueType: valueType, &fbb)
    TelegramCore_TelegramMediaFileAttribute.add(value: value, &fbb)
    return TelegramCore_TelegramMediaFileAttribute.endTelegramMediaFileAttribute(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(unionKey: VTOFFSET.valueType.p, unionField: VTOFFSET.value.p, unionKeyName: "valueType", fieldName: "value", required: true, completion: { (verifier, key: TelegramCore_TelegramMediaFileAttribute_Value, pos) in
      switch key {
      case .none_:
        break // NOTE - SWIFT doesnt support none
      case .telegrammediafileattributeFilename:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_FileName>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_FileName.self)
      case .telegrammediafileattributeSticker:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_Sticker>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_Sticker.self)
      case .telegrammediafileattributeImagesize:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_ImageSize>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_ImageSize.self)
      case .telegrammediafileattributeAnimated:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_Animated>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_Animated.self)
      case .telegrammediafileattributeVideo:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_Video>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_Video.self)
      case .telegrammediafileattributeAudio:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_Audio>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_Audio.self)
      case .telegrammediafileattributeHaslinkedstickers:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_HasLinkedStickers>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_HasLinkedStickers.self)
      case .telegrammediafileattributeHintfileislarge:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_HintFileIsLarge>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_HintFileIsLarge.self)
      case .telegrammediafileattributeHintisvalidated:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_HintIsValidated>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_HintIsValidated.self)
      case .telegrammediafileattributeNopremium:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_NoPremium>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_NoPremium.self)
      case .telegrammediafileattributeCustomemoji:
        try ForwardOffset<TelegramCore_TelegramMediaFileAttribute_CustomEmoji>.verify(&verifier, at: pos, of: TelegramCore_TelegramMediaFileAttribute_CustomEmoji.self)
      }
    })
    _v.finish()
  }
}
