// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_TelegramMediaFile: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case fileId = 4
    case partialReference = 6
    case resource = 8
    case previewRepresentations = 10
    case videoThumbnails = 12
    case videoCover = 14
    case immediateThumbnailData = 16
    case mimeType = 18
    case size = 20
    case attributes = 22
    case alternativeRepresentations = 24
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var fileId: TelegramCore_MediaId! { let o = _accessor.offset(VTOFFSET.fileId.v); return _accessor.readBuffer(of: TelegramCore_MediaId.self, at: o) }
  public var mutableFileId: TelegramCore_MediaId_Mutable! { let o = _accessor.offset(VTOFFSET.fileId.v); return TelegramCore_MediaId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var partialReference: TelegramCore_PartialMediaReference? { let o = _accessor.offset(VTOFFSET.partialReference.v); return o == 0 ? nil : TelegramCore_PartialMediaReference(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var resource: TelegramCore_TelegramMediaResource! { let o = _accessor.offset(VTOFFSET.resource.v); return TelegramCore_TelegramMediaResource(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasPreviewRepresentations: Bool { let o = _accessor.offset(VTOFFSET.previewRepresentations.v); return o == 0 ? false : true }
  public var previewRepresentationsCount: Int32 { let o = _accessor.offset(VTOFFSET.previewRepresentations.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func previewRepresentations(at index: Int32) -> TelegramCore_TelegramMediaImageRepresentation? { let o = _accessor.offset(VTOFFSET.previewRepresentations.v); return o == 0 ? nil : TelegramCore_TelegramMediaImageRepresentation(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasVideoThumbnails: Bool { let o = _accessor.offset(VTOFFSET.videoThumbnails.v); return o == 0 ? false : true }
  public var videoThumbnailsCount: Int32 { let o = _accessor.offset(VTOFFSET.videoThumbnails.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func videoThumbnails(at index: Int32) -> TelegramCore_VideoThumbnail? { let o = _accessor.offset(VTOFFSET.videoThumbnails.v); return o == 0 ? nil : TelegramCore_VideoThumbnail(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var videoCover: TelegramCore_TelegramMediaImage? { let o = _accessor.offset(VTOFFSET.videoCover.v); return o == 0 ? nil : TelegramCore_TelegramMediaImage(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasImmediateThumbnailData: Bool { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? false : true }
  public var immediateThumbnailDataCount: Int32 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func immediateThumbnailData(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var immediateThumbnailData: [UInt8] { return _accessor.getVector(at: VTOFFSET.immediateThumbnailData.v) ?? [] }
  public var mimeType: String! { let o = _accessor.offset(VTOFFSET.mimeType.v); return _accessor.string(at: o) }
  public var mimeTypeSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.mimeType.v) }
  public var size: Int64 { let o = _accessor.offset(VTOFFSET.size.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var hasAttributes: Bool { let o = _accessor.offset(VTOFFSET.attributes.v); return o == 0 ? false : true }
  public var attributesCount: Int32 { let o = _accessor.offset(VTOFFSET.attributes.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func attributes(at index: Int32) -> TelegramCore_TelegramMediaFileAttribute? { let o = _accessor.offset(VTOFFSET.attributes.v); return o == 0 ? nil : TelegramCore_TelegramMediaFileAttribute(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var hasAlternativeRepresentations: Bool { let o = _accessor.offset(VTOFFSET.alternativeRepresentations.v); return o == 0 ? false : true }
  public var alternativeRepresentationsCount: Int32 { let o = _accessor.offset(VTOFFSET.alternativeRepresentations.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func alternativeRepresentations(at index: Int32) -> TelegramCore_TelegramMediaFile? { let o = _accessor.offset(VTOFFSET.alternativeRepresentations.v); return o == 0 ? nil : TelegramCore_TelegramMediaFile(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public static func startTelegramMediaFile(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 11) }
  public static func add(fileId: TelegramCore_MediaId?, _ fbb: inout FlatBufferBuilder) { guard let fileId = fileId else { return }; fbb.create(struct: fileId, position: VTOFFSET.fileId.p) }
  public static func add(partialReference: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: partialReference, at: VTOFFSET.partialReference.p) }
  public static func add(resource: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resource, at: VTOFFSET.resource.p) }
  public static func addVectorOf(previewRepresentations: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: previewRepresentations, at: VTOFFSET.previewRepresentations.p) }
  public static func addVectorOf(videoThumbnails: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: videoThumbnails, at: VTOFFSET.videoThumbnails.p) }
  public static func add(videoCover: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: videoCover, at: VTOFFSET.videoCover.p) }
  public static func addVectorOf(immediateThumbnailData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: immediateThumbnailData, at: VTOFFSET.immediateThumbnailData.p) }
  public static func add(mimeType: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: mimeType, at: VTOFFSET.mimeType.p) }
  public static func add(size: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: size, def: 0, at: VTOFFSET.size.p) }
  public static func addVectorOf(attributes: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: attributes, at: VTOFFSET.attributes.p) }
  public static func addVectorOf(alternativeRepresentations: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: alternativeRepresentations, at: VTOFFSET.alternativeRepresentations.p) }
  public static func endTelegramMediaFile(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 8, 18]); return end }
  public static func createTelegramMediaFile(
    _ fbb: inout FlatBufferBuilder,
    fileId: TelegramCore_MediaId,
    partialReferenceOffset partialReference: Offset = Offset(),
    resourceOffset resource: Offset,
    previewRepresentationsVectorOffset previewRepresentations: Offset = Offset(),
    videoThumbnailsVectorOffset videoThumbnails: Offset = Offset(),
    videoCoverOffset videoCover: Offset = Offset(),
    immediateThumbnailDataVectorOffset immediateThumbnailData: Offset = Offset(),
    mimeTypeOffset mimeType: Offset,
    size: Int64 = 0,
    attributesVectorOffset attributes: Offset = Offset(),
    alternativeRepresentationsVectorOffset alternativeRepresentations: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaFile.startTelegramMediaFile(&fbb)
    TelegramCore_TelegramMediaFile.add(fileId: fileId, &fbb)
    TelegramCore_TelegramMediaFile.add(partialReference: partialReference, &fbb)
    TelegramCore_TelegramMediaFile.add(resource: resource, &fbb)
    TelegramCore_TelegramMediaFile.addVectorOf(previewRepresentations: previewRepresentations, &fbb)
    TelegramCore_TelegramMediaFile.addVectorOf(videoThumbnails: videoThumbnails, &fbb)
    TelegramCore_TelegramMediaFile.add(videoCover: videoCover, &fbb)
    TelegramCore_TelegramMediaFile.addVectorOf(immediateThumbnailData: immediateThumbnailData, &fbb)
    TelegramCore_TelegramMediaFile.add(mimeType: mimeType, &fbb)
    TelegramCore_TelegramMediaFile.add(size: size, &fbb)
    TelegramCore_TelegramMediaFile.addVectorOf(attributes: attributes, &fbb)
    TelegramCore_TelegramMediaFile.addVectorOf(alternativeRepresentations: alternativeRepresentations, &fbb)
    return TelegramCore_TelegramMediaFile.endTelegramMediaFile(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.fileId.p, fieldName: "fileId", required: true, type: TelegramCore_MediaId.self)
    try _v.visit(field: VTOFFSET.partialReference.p, fieldName: "partialReference", required: false, type: ForwardOffset<TelegramCore_PartialMediaReference>.self)
    try _v.visit(field: VTOFFSET.resource.p, fieldName: "resource", required: true, type: ForwardOffset<TelegramCore_TelegramMediaResource>.self)
    try _v.visit(field: VTOFFSET.previewRepresentations.p, fieldName: "previewRepresentations", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramMediaImageRepresentation>, TelegramCore_TelegramMediaImageRepresentation>>.self)
    try _v.visit(field: VTOFFSET.videoThumbnails.p, fieldName: "videoThumbnails", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_VideoThumbnail>, TelegramCore_VideoThumbnail>>.self)
    try _v.visit(field: VTOFFSET.videoCover.p, fieldName: "videoCover", required: false, type: ForwardOffset<TelegramCore_TelegramMediaImage>.self)
    try _v.visit(field: VTOFFSET.immediateThumbnailData.p, fieldName: "immediateThumbnailData", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.mimeType.p, fieldName: "mimeType", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.size.p, fieldName: "size", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.attributes.p, fieldName: "attributes", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramMediaFileAttribute>, TelegramCore_TelegramMediaFileAttribute>>.self)
    try _v.visit(field: VTOFFSET.alternativeRepresentations.p, fieldName: "alternativeRepresentations", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramMediaFile>, TelegramCore_TelegramMediaFile>>.self)
    _v.finish()
  }
}
