// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_BotUserInfo: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case flags = 4
    case inlinePlaceholder = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var inlinePlaceholder: String? { let o = _accessor.offset(VTOFFSET.inlinePlaceholder.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var inlinePlaceholderSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.inlinePlaceholder.v) }
  public static func startBotUserInfo(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 2) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func add(inlinePlaceholder: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: inlinePlaceholder, at: VTOFFSET.inlinePlaceholder.p) }
  public static func endBotUserInfo(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createBotUserInfo(
    _ fbb: inout FlatBufferBuilder,
    flags: Int32 = 0,
    inlinePlaceholderOffset inlinePlaceholder: Offset = Offset()
  ) -> Offset {
    let __start = TelegramCore_BotUserInfo.startBotUserInfo(&fbb)
    TelegramCore_BotUserInfo.add(flags: flags, &fbb)
    TelegramCore_BotUserInfo.add(inlinePlaceholder: inlinePlaceholder, &fbb)
    return TelegramCore_BotUserInfo.endBotUserInfo(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.inlinePlaceholder.p, fieldName: "inlinePlaceholder", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct TelegramCore_TelegramUser: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case accessHash = 6
    case firstName = 8
    case lastName = 10
    case username = 12
    case phone = 14
    case photo = 16
    case botInfo = 18
    case restrictionInfo = 20
    case flags = 22
    case emojiStatus = 24
    case usernames = 26
    case storiesHidden = 28
    case nameColor = 30
    case backgroundEmojiId = 32
    case profileColor = 34
    case profileBackgroundEmojiId = 36
    case subscriberCount = 38
    case verificationIconFileId = 40
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: TelegramCore_PeerId! { let o = _accessor.offset(VTOFFSET.id.v); return _accessor.readBuffer(of: TelegramCore_PeerId.self, at: o) }
  public var mutableId: TelegramCore_PeerId_Mutable! { let o = _accessor.offset(VTOFFSET.id.v); return TelegramCore_PeerId_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var accessHash: TelegramCore_TelegramPeerAccessHash? { let o = _accessor.offset(VTOFFSET.accessHash.v); return o == 0 ? nil : TelegramCore_TelegramPeerAccessHash(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var firstName: String? { let o = _accessor.offset(VTOFFSET.firstName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var firstNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.firstName.v) }
  public var lastName: String? { let o = _accessor.offset(VTOFFSET.lastName.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var lastNameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.lastName.v) }
  public var username: String? { let o = _accessor.offset(VTOFFSET.username.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var usernameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.username.v) }
  public var phone: String? { let o = _accessor.offset(VTOFFSET.phone.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var phoneSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.phone.v) }
  public var hasPhoto: Bool { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? false : true }
  public var photoCount: Int32 { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func photo(at index: Int32) -> TelegramCore_TelegramMediaImageRepresentation? { let o = _accessor.offset(VTOFFSET.photo.v); return o == 0 ? nil : TelegramCore_TelegramMediaImageRepresentation(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var botInfo: TelegramCore_BotUserInfo? { let o = _accessor.offset(VTOFFSET.botInfo.v); return o == 0 ? nil : TelegramCore_BotUserInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var restrictionInfo: TelegramCore_PeerAccessRestrictionInfo? { let o = _accessor.offset(VTOFFSET.restrictionInfo.v); return o == 0 ? nil : TelegramCore_PeerAccessRestrictionInfo(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var flags: Int32 { let o = _accessor.offset(VTOFFSET.flags.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var emojiStatus: TelegramCore_PeerEmojiStatus? { let o = _accessor.offset(VTOFFSET.emojiStatus.v); return o == 0 ? nil : TelegramCore_PeerEmojiStatus(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasUsernames: Bool { let o = _accessor.offset(VTOFFSET.usernames.v); return o == 0 ? false : true }
  public var usernamesCount: Int32 { let o = _accessor.offset(VTOFFSET.usernames.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func usernames(at index: Int32) -> TelegramCore_TelegramPeerUsername? { let o = _accessor.offset(VTOFFSET.usernames.v); return o == 0 ? nil : TelegramCore_TelegramPeerUsername(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var storiesHidden: TelegramCore_OptionalBool? { let o = _accessor.offset(VTOFFSET.storiesHidden.v); return o == 0 ? nil : _accessor.readBuffer(of: TelegramCore_OptionalBool.self, at: o) }
  public var mutableStoriesHidden: TelegramCore_OptionalBool_Mutable? { let o = _accessor.offset(VTOFFSET.storiesHidden.v); return o == 0 ? nil : TelegramCore_OptionalBool_Mutable(_accessor.bb, o: o + _accessor.position) }
  public var nameColor: TelegramCore_PeerNameColor? { let o = _accessor.offset(VTOFFSET.nameColor.v); return o == 0 ? nil : TelegramCore_PeerNameColor(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var backgroundEmojiId: Int64 { let o = _accessor.offset(VTOFFSET.backgroundEmojiId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var profileColor: TelegramCore_PeerNameColor? { let o = _accessor.offset(VTOFFSET.profileColor.v); return o == 0 ? nil : TelegramCore_PeerNameColor(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var profileBackgroundEmojiId: Int64 { let o = _accessor.offset(VTOFFSET.profileBackgroundEmojiId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public var subscriberCount: Int32 { let o = _accessor.offset(VTOFFSET.subscriberCount.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var verificationIconFileId: Int64 { let o = _accessor.offset(VTOFFSET.verificationIconFileId.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o) }
  public static func startTelegramUser(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 19) }
  public static func add(id: TelegramCore_PeerId?, _ fbb: inout FlatBufferBuilder) { guard let id = id else { return }; fbb.create(struct: id, position: VTOFFSET.id.p) }
  public static func add(accessHash: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: accessHash, at: VTOFFSET.accessHash.p) }
  public static func add(firstName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: firstName, at: VTOFFSET.firstName.p) }
  public static func add(lastName: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: lastName, at: VTOFFSET.lastName.p) }
  public static func add(username: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: username, at: VTOFFSET.username.p) }
  public static func add(phone: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: phone, at: VTOFFSET.phone.p) }
  public static func addVectorOf(photo: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: photo, at: VTOFFSET.photo.p) }
  public static func add(botInfo: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: botInfo, at: VTOFFSET.botInfo.p) }
  public static func add(restrictionInfo: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: restrictionInfo, at: VTOFFSET.restrictionInfo.p) }
  public static func add(flags: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: flags, def: 0, at: VTOFFSET.flags.p) }
  public static func add(emojiStatus: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: emojiStatus, at: VTOFFSET.emojiStatus.p) }
  public static func addVectorOf(usernames: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: usernames, at: VTOFFSET.usernames.p) }
  public static func add(storiesHidden: TelegramCore_OptionalBool?, _ fbb: inout FlatBufferBuilder) { guard let storiesHidden = storiesHidden else { return }; fbb.create(struct: storiesHidden, position: VTOFFSET.storiesHidden.p) }
  public static func add(nameColor: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: nameColor, at: VTOFFSET.nameColor.p) }
  public static func add(backgroundEmojiId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: backgroundEmojiId, def: 0, at: VTOFFSET.backgroundEmojiId.p) }
  public static func add(profileColor: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: profileColor, at: VTOFFSET.profileColor.p) }
  public static func add(profileBackgroundEmojiId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: profileBackgroundEmojiId, def: 0, at: VTOFFSET.profileBackgroundEmojiId.p) }
  public static func add(subscriberCount: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: subscriberCount, def: 0, at: VTOFFSET.subscriberCount.p) }
  public static func add(verificationIconFileId: Int64, _ fbb: inout FlatBufferBuilder) { fbb.add(element: verificationIconFileId, def: 0, at: VTOFFSET.verificationIconFileId.p) }
  public static func endTelegramUser(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4, 16]); return end }
  public static func createTelegramUser(
    _ fbb: inout FlatBufferBuilder,
    id: TelegramCore_PeerId,
    accessHashOffset accessHash: Offset = Offset(),
    firstNameOffset firstName: Offset = Offset(),
    lastNameOffset lastName: Offset = Offset(),
    usernameOffset username: Offset = Offset(),
    phoneOffset phone: Offset = Offset(),
    photoVectorOffset photo: Offset,
    botInfoOffset botInfo: Offset = Offset(),
    restrictionInfoOffset restrictionInfo: Offset = Offset(),
    flags: Int32 = 0,
    emojiStatusOffset emojiStatus: Offset = Offset(),
    usernamesVectorOffset usernames: Offset = Offset(),
    storiesHidden: TelegramCore_OptionalBool? = nil,
    nameColorOffset nameColor: Offset = Offset(),
    backgroundEmojiId: Int64 = 0,
    profileColorOffset profileColor: Offset = Offset(),
    profileBackgroundEmojiId: Int64 = 0,
    subscriberCount: Int32 = 0,
    verificationIconFileId: Int64 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramUser.startTelegramUser(&fbb)
    TelegramCore_TelegramUser.add(id: id, &fbb)
    TelegramCore_TelegramUser.add(accessHash: accessHash, &fbb)
    TelegramCore_TelegramUser.add(firstName: firstName, &fbb)
    TelegramCore_TelegramUser.add(lastName: lastName, &fbb)
    TelegramCore_TelegramUser.add(username: username, &fbb)
    TelegramCore_TelegramUser.add(phone: phone, &fbb)
    TelegramCore_TelegramUser.addVectorOf(photo: photo, &fbb)
    TelegramCore_TelegramUser.add(botInfo: botInfo, &fbb)
    TelegramCore_TelegramUser.add(restrictionInfo: restrictionInfo, &fbb)
    TelegramCore_TelegramUser.add(flags: flags, &fbb)
    TelegramCore_TelegramUser.add(emojiStatus: emojiStatus, &fbb)
    TelegramCore_TelegramUser.addVectorOf(usernames: usernames, &fbb)
    TelegramCore_TelegramUser.add(storiesHidden: storiesHidden, &fbb)
    TelegramCore_TelegramUser.add(nameColor: nameColor, &fbb)
    TelegramCore_TelegramUser.add(backgroundEmojiId: backgroundEmojiId, &fbb)
    TelegramCore_TelegramUser.add(profileColor: profileColor, &fbb)
    TelegramCore_TelegramUser.add(profileBackgroundEmojiId: profileBackgroundEmojiId, &fbb)
    TelegramCore_TelegramUser.add(subscriberCount: subscriberCount, &fbb)
    TelegramCore_TelegramUser.add(verificationIconFileId: verificationIconFileId, &fbb)
    return TelegramCore_TelegramUser.endTelegramUser(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: true, type: TelegramCore_PeerId.self)
    try _v.visit(field: VTOFFSET.accessHash.p, fieldName: "accessHash", required: false, type: ForwardOffset<TelegramCore_TelegramPeerAccessHash>.self)
    try _v.visit(field: VTOFFSET.firstName.p, fieldName: "firstName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.lastName.p, fieldName: "lastName", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.username.p, fieldName: "username", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.phone.p, fieldName: "phone", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.photo.p, fieldName: "photo", required: true, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramMediaImageRepresentation>, TelegramCore_TelegramMediaImageRepresentation>>.self)
    try _v.visit(field: VTOFFSET.botInfo.p, fieldName: "botInfo", required: false, type: ForwardOffset<TelegramCore_BotUserInfo>.self)
    try _v.visit(field: VTOFFSET.restrictionInfo.p, fieldName: "restrictionInfo", required: false, type: ForwardOffset<TelegramCore_PeerAccessRestrictionInfo>.self)
    try _v.visit(field: VTOFFSET.flags.p, fieldName: "flags", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.emojiStatus.p, fieldName: "emojiStatus", required: false, type: ForwardOffset<TelegramCore_PeerEmojiStatus>.self)
    try _v.visit(field: VTOFFSET.usernames.p, fieldName: "usernames", required: false, type: ForwardOffset<Vector<ForwardOffset<TelegramCore_TelegramPeerUsername>, TelegramCore_TelegramPeerUsername>>.self)
    try _v.visit(field: VTOFFSET.storiesHidden.p, fieldName: "storiesHidden", required: false, type: TelegramCore_OptionalBool.self)
    try _v.visit(field: VTOFFSET.nameColor.p, fieldName: "nameColor", required: false, type: ForwardOffset<TelegramCore_PeerNameColor>.self)
    try _v.visit(field: VTOFFSET.backgroundEmojiId.p, fieldName: "backgroundEmojiId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.profileColor.p, fieldName: "profileColor", required: false, type: ForwardOffset<TelegramCore_PeerNameColor>.self)
    try _v.visit(field: VTOFFSET.profileBackgroundEmojiId.p, fieldName: "profileBackgroundEmojiId", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.subscriberCount.p, fieldName: "subscriberCount", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.verificationIconFileId.p, fieldName: "verificationIconFileId", required: false, type: Int64.self)
    _v.finish()
  }
}

