// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_TelegramChatAdminRights: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case rights = 4
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var rights: Int32 { let o = _accessor.offset(VTOFFSET.rights.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public static func startTelegramChatAdminRights(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 1) }
  public static func add(rights: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: rights, def: 0, at: VTOFFSET.rights.p) }
  public static func endTelegramChatAdminRights(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createTelegramChatAdminRights(
    _ fbb: inout FlatBufferBuilder,
    rights: Int32 = 0
  ) -> Offset {
    let __start = TelegramCore_TelegramChatAdminRights.startTelegramChatAdminRights(&fbb)
    TelegramCore_TelegramChatAdminRights.add(rights: rights, &fbb)
    return TelegramCore_TelegramChatAdminRights.endTelegramChatAdminRights(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.rights.p, fieldName: "rights", required: false, type: Int32.self)
    _v.finish()
  }
}
