// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum TelegramCore_TelegramMediaImageRepresentation_TypeHint: Int32, Enum, Verifiable {
  public typealias T = Int32
  public static var byteSize: Int { return MemoryLayout<Int32>.size }
  public var value: Int32 { return self.rawValue }
  case generic = 0
  case animated = 1
  case video = 2

  public static var max: TelegramCore_TelegramMediaImageRepresentation_TypeHint { return .video }
  public static var min: TelegramCore_TelegramMediaImageRepresentation_TypeHint { return .generic }
}


public struct TelegramCore_TelegramMediaImageRepresentation: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case width = 4
    case height = 6
    case resource = 8
    case progressiveSizes = 10
    case immediateThumbnailData = 12
    case hasVideo = 14
    case isPersonal = 16
    case typeHint = 18
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var width: Int32 { let o = _accessor.offset(VTOFFSET.width.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var height: Int32 { let o = _accessor.offset(VTOFFSET.height.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var resource: TelegramCore_TelegramMediaResource! { let o = _accessor.offset(VTOFFSET.resource.v); return TelegramCore_TelegramMediaResource(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var hasProgressiveSizes: Bool { let o = _accessor.offset(VTOFFSET.progressiveSizes.v); return o == 0 ? false : true }
  public var progressiveSizesCount: Int32 { let o = _accessor.offset(VTOFFSET.progressiveSizes.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func progressiveSizes(at index: Int32) -> Int32 { let o = _accessor.offset(VTOFFSET.progressiveSizes.v); return o == 0 ? 0 : _accessor.directRead(of: Int32.self, offset: _accessor.vector(at: o) + index * 4) }
  public var progressiveSizes: [Int32] { return _accessor.getVector(at: VTOFFSET.progressiveSizes.v) ?? [] }
  public var hasImmediateThumbnailData: Bool { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? false : true }
  public var immediateThumbnailDataCount: Int32 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func immediateThumbnailData(at index: Int32) -> UInt8 { let o = _accessor.offset(VTOFFSET.immediateThumbnailData.v); return o == 0 ? 0 : _accessor.directRead(of: UInt8.self, offset: _accessor.vector(at: o) + index * 1) }
  public var immediateThumbnailData: [UInt8] { return _accessor.getVector(at: VTOFFSET.immediateThumbnailData.v) ?? [] }
  public var hasVideo: Bool { let o = _accessor.offset(VTOFFSET.hasVideo.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var isPersonal: Bool { let o = _accessor.offset(VTOFFSET.isPersonal.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var typeHint: TelegramCore_TelegramMediaImageRepresentation_TypeHint { let o = _accessor.offset(VTOFFSET.typeHint.v); return o == 0 ? .generic : TelegramCore_TelegramMediaImageRepresentation_TypeHint(rawValue: _accessor.readBuffer(of: Int32.self, at: o)) ?? .generic }
  public static func startTelegramMediaImageRepresentation(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 8) }
  public static func add(width: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: width, def: 0, at: VTOFFSET.width.p) }
  public static func add(height: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: height, def: 0, at: VTOFFSET.height.p) }
  public static func add(resource: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resource, at: VTOFFSET.resource.p) }
  public static func addVectorOf(progressiveSizes: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: progressiveSizes, at: VTOFFSET.progressiveSizes.p) }
  public static func addVectorOf(immediateThumbnailData: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: immediateThumbnailData, at: VTOFFSET.immediateThumbnailData.p) }
  public static func add(hasVideo: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: hasVideo, def: false,
   at: VTOFFSET.hasVideo.p) }
  public static func add(isPersonal: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: isPersonal, def: false,
   at: VTOFFSET.isPersonal.p) }
  public static func add(typeHint: TelegramCore_TelegramMediaImageRepresentation_TypeHint, _ fbb: inout FlatBufferBuilder) { fbb.add(element: typeHint.rawValue, def: 0, at: VTOFFSET.typeHint.p) }
  public static func endTelegramMediaImageRepresentation(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [8]); return end }
  public static func createTelegramMediaImageRepresentation(
    _ fbb: inout FlatBufferBuilder,
    width: Int32 = 0,
    height: Int32 = 0,
    resourceOffset resource: Offset,
    progressiveSizesVectorOffset progressiveSizes: Offset = Offset(),
    immediateThumbnailDataVectorOffset immediateThumbnailData: Offset = Offset(),
    hasVideo: Bool = false,
    isPersonal: Bool = false,
    typeHint: TelegramCore_TelegramMediaImageRepresentation_TypeHint = .generic
  ) -> Offset {
    let __start = TelegramCore_TelegramMediaImageRepresentation.startTelegramMediaImageRepresentation(&fbb)
    TelegramCore_TelegramMediaImageRepresentation.add(width: width, &fbb)
    TelegramCore_TelegramMediaImageRepresentation.add(height: height, &fbb)
    TelegramCore_TelegramMediaImageRepresentation.add(resource: resource, &fbb)
    TelegramCore_TelegramMediaImageRepresentation.addVectorOf(progressiveSizes: progressiveSizes, &fbb)
    TelegramCore_TelegramMediaImageRepresentation.addVectorOf(immediateThumbnailData: immediateThumbnailData, &fbb)
    TelegramCore_TelegramMediaImageRepresentation.add(hasVideo: hasVideo, &fbb)
    TelegramCore_TelegramMediaImageRepresentation.add(isPersonal: isPersonal, &fbb)
    TelegramCore_TelegramMediaImageRepresentation.add(typeHint: typeHint, &fbb)
    return TelegramCore_TelegramMediaImageRepresentation.endTelegramMediaImageRepresentation(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.width.p, fieldName: "width", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.height.p, fieldName: "height", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.resource.p, fieldName: "resource", required: true, type: ForwardOffset<TelegramCore_TelegramMediaResource>.self)
    try _v.visit(field: VTOFFSET.progressiveSizes.p, fieldName: "progressiveSizes", required: false, type: ForwardOffset<Vector<Int32, Int32>>.self)
    try _v.visit(field: VTOFFSET.immediateThumbnailData.p, fieldName: "immediateThumbnailData", required: false, type: ForwardOffset<Vector<UInt8, UInt8>>.self)
    try _v.visit(field: VTOFFSET.hasVideo.p, fieldName: "hasVideo", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.isPersonal.p, fieldName: "isPersonal", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.typeHint.p, fieldName: "typeHint", required: false, type: TelegramCore_TelegramMediaImageRepresentation_TypeHint.self)
    _v.finish()
  }
}

