// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct TelegramCore_VideoThumbnail: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_24_12_23() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case width = 4
    case height = 6
    case resource = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var width: Int32 { let o = _accessor.offset(VTOFFSET.width.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var height: Int32 { let o = _accessor.offset(VTOFFSET.height.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var resource: TelegramCore_TelegramMediaResource! { let o = _accessor.offset(VTOFFSET.resource.v); return TelegramCore_TelegramMediaResource(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startVideoThumbnail(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(width: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: width, def: 0, at: VTOFFSET.width.p) }
  public static func add(height: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: height, def: 0, at: VTOFFSET.height.p) }
  public static func add(resource: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: resource, at: VTOFFSET.resource.p) }
  public static func endVideoThumbnail(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [8]); return end }
  public static func createVideoThumbnail(
    _ fbb: inout FlatBufferBuilder,
    width: Int32 = 0,
    height: Int32 = 0,
    resourceOffset resource: Offset
  ) -> Offset {
    let __start = TelegramCore_VideoThumbnail.startVideoThumbnail(&fbb)
    TelegramCore_VideoThumbnail.add(width: width, &fbb)
    TelegramCore_VideoThumbnail.add(height: height, &fbb)
    TelegramCore_VideoThumbnail.add(resource: resource, &fbb)
    return TelegramCore_VideoThumbnail.endVideoThumbnail(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.width.p, fieldName: "width", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.height.p, fieldName: "height", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.resource.p, fieldName: "resource", required: true, type: ForwardOffset<TelegramCore_TelegramMediaResource>.self)
    _v.finish()
  }
}

