import QuillInteractionSmokeSupport
import QuillUIGtk

private typealias QuillGtkInteractionSmokeApp = QuillBackendInteractionSmokeApp<QuillGtkBackend>

QuillGtkApp.run(QuillGtkInteractionSmokeApp.self)
