#!/usr/bin/env bash
set -euo pipefail

ARTIFACT_DIR="${1:-}"
APP_ID="${2:-}"
PRODUCT_NAME="${3:-}"
DISPLAY_NAME="${4:-}"

usage() {
  cat <<MSG
Usage: $(basename "$0") ARTIFACT_DIR APP_ID PRODUCT_NAME [DISPLAY_NAME]

Validates the Linux desktop metadata generated by package-swiftui-linux-app.sh.
MSG
}

if [[ -z "$ARTIFACT_DIR" || -z "$APP_ID" || -z "$PRODUCT_NAME" ]]; then
  usage >&2
  exit 64
fi

desktop_file="$ARTIFACT_DIR/share/applications/$APP_ID.desktop"
metainfo_file="$ARTIFACT_DIR/share/metainfo/$APP_ID.metainfo.xml"
metadata_file="$ARTIFACT_DIR/metadata/quillui-release.env"

for path in "$desktop_file" "$metainfo_file" "$metadata_file"; do
  if [[ ! -f "$path" ]]; then
    echo "Missing packaged app metadata file: $path" >&2
    exit 66
  fi
done

grep -Fx '[Desktop Entry]' "$desktop_file" >/dev/null
grep -Fx 'Type=Application' "$desktop_file" >/dev/null
grep -Fx "Exec=$PRODUCT_NAME" "$desktop_file" >/dev/null
grep -Fx "Icon=$APP_ID" "$desktop_file" >/dev/null
grep -Fx 'Terminal=false' "$desktop_file" >/dev/null
grep -Fx "StartupWMClass=$PRODUCT_NAME" "$desktop_file" >/dev/null
grep -Fx "app_id=$APP_ID" "$metadata_file" >/dev/null
grep -Fx "product=$PRODUCT_NAME" "$metadata_file" >/dev/null
grep -Fx "desktop_file=$desktop_file" "$metadata_file" >/dev/null
grep -Fx "metainfo=$metainfo_file" "$metadata_file" >/dev/null

if [[ -n "$DISPLAY_NAME" ]]; then
  grep -Fx "Name=$DISPLAY_NAME" "$desktop_file" >/dev/null
  grep -Fx "display_name=$DISPLAY_NAME" "$metadata_file" >/dev/null
fi

python3 - "$metainfo_file" "$APP_ID" "$PRODUCT_NAME" "$DISPLAY_NAME" <<'PY'
import sys
import xml.etree.ElementTree as ET

metainfo_path, app_id, product_name, display_name = sys.argv[1:5]
root = ET.parse(metainfo_path).getroot()

def require(condition, message):
    if not condition:
        raise SystemExit(message)

def child_text(name):
    child = root.find(name)
    return child.text.strip() if child is not None and child.text else ""

require(root.tag == "component", f"Unexpected AppStream root: {root.tag}")
require(root.attrib.get("type") == "desktop-application", "AppStream component is not desktop-application")
require(child_text("id") == app_id, "AppStream id does not match app id")
if display_name:
    require(child_text("name") == display_name, "AppStream name does not match display name")
require(child_text("summary"), "AppStream summary is empty")
launchable = root.find("launchable")
require(launchable is not None, "AppStream launchable is missing")
require(launchable.attrib.get("type") == "desktop-id", "AppStream launchable is not desktop-id")
require((launchable.text or "").strip() == f"{app_id}.desktop", "AppStream launchable desktop id mismatch")
binary = root.find("provides/binary")
require(binary is not None and (binary.text or "").strip() == product_name, "AppStream binary provider mismatch")
PY

printf 'Linux app metadata ok: %s\n' "$APP_ID"
