#!/usr/bin/env python3
import re
import sys
from pathlib import Path


def swift_identifier(asset_name: str) -> str:
    output: list[str] = []
    capitalize_next = False
    for character in asset_name:
        if character in {".", " ", "-", "/", "_"}:
            capitalize_next = True
            continue
        if not output:
            if character.isalpha() or character == "_":
                output.append(character.lower())
            elif character.isdigit():
                output.append("_")
                output.append(character)
            else:
                output.append("_")
            capitalize_next = False
            continue
        if not (character.isalpha() or character.isdigit() or character == "_"):
            output.append("_")
            capitalize_next = False
            continue
        output.append(character.upper() if capitalize_next and character.isalpha() else character)
        capitalize_next = False
    return "".join(output) or "_"


def image_asset_names(package_dir: Path) -> list[str]:
    names: set[str] = set()
    for candidate in package_dir.rglob("*"):
        if candidate.is_dir() and candidate.suffix in {".imageset", ".symbolset"}:
            names.add(candidate.stem)
    return sorted(names)


def source_directories_that_need_symbols(package_dir: Path) -> list[Path]:
    directories: set[Path] = set()
    for swift_file in package_dir.rglob("*.swift"):
        relative_parts = swift_file.relative_to(package_dir).parts
        if any(part in {".build", ".git", ".swiftpm"} for part in relative_parts):
            continue
        try:
            text = swift_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = swift_file.read_text(encoding="utf-8", errors="ignore")
        if "ImageResource" in text or "NSImage(resource:" in text:
            directories.add(swift_file.parent)
    return sorted(directories)


def generated_source(asset_names: list[str]) -> str:
    lines = [
        "// Generated by generate-telegram-image-resource-symbols.py. Do not edit.",
        "import AppKit",
        "",
        "public extension ImageResource {",
    ]
    seen_identifiers: set[str] = set()
    for asset_name in asset_names:
        identifier = swift_identifier(asset_name)
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", identifier):
            continue
        if identifier in seen_identifiers:
            continue
        seen_identifiers.add(identifier)
        escaped_name = asset_name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    static var {identifier}: ImageResource {{ ImageResource(name: "{escaped_name}", bundle: .module) }}')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate-telegram-image-resource-symbols.py PACKAGE_DIR")
    package_dir = Path(sys.argv[1])
    assets = image_asset_names(package_dir)
    if not assets:
        return
    source = generated_source(assets)
    for directory in source_directories_that_need_symbols(package_dir):
        (directory / "QuillGeneratedImageResourceSymbols.swift").write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
