#!/usr/bin/env bash
set -euo pipefail

if (( $# < 2 )); then
  cat >&2 <<'MSG'
Usage: scripts/generate-hashable-identity-shims.sh OUTPUT.swift Type:identityProperty[:idProperty:idType] [...]

Generates Swift extensions that make model types Hashable and Equatable by a
stable identity property. This is useful for generated Linux builds where
SwiftData model classes are lowered to QuillData classes, but app UI still uses
those models in Picker, ForEach, Set, or dictionary contexts.

Example:

  scripts/generate-hashable-identity-shims.sh GeneratedModelHashing.swift \
    ConversationSD:id LanguageModelSD:name:id:String
MSG
  exit 64
fi

OUTPUT_FILE="$1"
shift

mkdir -p "$(dirname "$OUTPUT_FILE")"

{
  cat <<'SWIFT'
// Generated by QuillUI's SwiftUI Linux build tooling.
// Do not edit by hand; adjust the profile identity specs instead.

import Foundation

SWIFT

  for spec in "$@"; do
    if [[ ! "$spec" =~ ^([A-Za-z_][A-Za-z0-9_]*):([A-Za-z_][A-Za-z0-9_]*)(:([A-Za-z_][A-Za-z0-9_]*):([A-Za-z_][A-Za-z0-9_]*))?$ ]]; then
      echo "Invalid hashable identity spec: $spec" >&2
      echo "Expected TypeName:identityProperty[:idProperty:idType], using Swift identifier names only." >&2
      exit 65
    fi

    type_name="${BASH_REMATCH[1]}"
    identity_property="${BASH_REMATCH[2]}"
    id_property="${BASH_REMATCH[4]:-}"
    id_type="${BASH_REMATCH[5]:-}"

    cat <<SWIFT
extension $type_name: Hashable {
SWIFT

    if [[ -n "$id_property" ]]; then
      cat <<SWIFT
    var $id_property: $id_type { $identity_property }

SWIFT
    fi

    cat <<SWIFT
    static func == (lhs: $type_name, rhs: $type_name) -> Bool {
        lhs.$identity_property == rhs.$identity_property
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine($identity_property)
    }
}

SWIFT
  done
} > "$OUTPUT_FILE"
