#!/usr/bin/env bash
# Remove stale AppKitLowering no-arg initializers from the disposable Signal app
# tree. The generic lowering pass sometimes inserts
# `nonisolated init() { super.init() }`; for subclasses with designated
# initializers this suppresses initializer inheritance, and for classes whose
# base init() is unavailable it creates an immediate compile failure.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ROOT="$ROOT/.upstream/signal-ios/Signal"

python3 - "$APP_ROOT" <<'PY'
import pathlib, re, sys

root = pathlib.Path(sys.argv[1])
if not root.exists():
    print("generated init lowering: upstream Signal tree not present")
    raise SystemExit(0)

simple_init = re.compile(r'^\s*nonisolated\s+(?:override\s+)?init\(\)\s*\{\s*super\.init\(\)\s*\}\s*$')
comment = re.compile(r'^\s*//')
removed = 0
files = 0

for path in root.rglob("*.swift"):
    lines = path.read_text(errors="replace").splitlines()
    out = []
    i = 0
    changed = False
    while i < len(lines):
        line = lines[i]
        if "Auto-generated by AppKitLowering: nonisolated init()" not in line:
            out.append(line)
            i += 1
            continue

        j = i + 1
        while j < len(lines) and comment.match(lines[j]):
            j += 1

        if j < len(lines) and simple_init.match(lines[j]):
            i = j + 1
            removed += 1
            changed = True
            continue

        out.append(line)
        i += 1

    if changed:
        path.write_text("\n".join(out) + ("\n" if lines else ""))
        files += 1

print(f"generated init lowering: removed {removed} simple init blocks across {files} files")
PY
