import QuillInteractionSmokeSupport
import QuillUI
import QuillUIQt

private typealias QuillQtInteractionSmokeApp = QuillBackendInteractionSmokeApp<QuillQtBackend>

QuillQtApp.run(QuillQtInteractionSmokeApp.self)
